<?php
require_once('../../../config/config.php');
die_login();
die_mod('T6');
$conn = conn();
die_conn($conn);

$msg = '';


$periode_tag = (isset($_REQUEST['periode_tag'])) ? to_periode($_REQUEST['periode_tag']) : '';

if ($_SERVER['REQUEST_METHOD'] == 'POST')
{
	try
	{
		$conn->begintrans();
		
		# BE CAREFULL TESTING ONLY
		#$conn->Execute("DELETE FROM KWT_PEMBAYARAN_AI WHERE PERIODE_TAG = '$periode_tag'");
		
		# INSERT TAGIHAN
		#$query = "SELECT COUNT(ID_PEMBAYARAN) AS TOTAL FROM KWT_PEMBAYARAN_AI WHERE PERIODE_TAG = '$periode_tag'";
		#ex_found($conn->Execute($query)->fields['TOTAL'], "Tagihan periode \"$periode_tag\" telah terdaftar.");
		
		# UPDATE STATUS BAYAR (UNTUK JUMLAH TAGIHAN = 0) [CANCEL]
		$query = "
		UPDATE KWT_PEMBAYARAN_AI_TEMP 
		SET
			STATUS_BAYAR = 1, 
			TGL_BAYAR_BANK = GETDATE(),
			TGL_BAYAR_SYS = GETDATE(), 
			USER_BAYAR = '1'
		WHERE 
			PERIODE_TAG = '$periode_tag' AND 
			(JUMLAH_AIR + ABONEMEN + JUMLAH_IPL + ADM + DENDA - DISKON_AIR - DISKON_IPL) < 1 
		";
		ex_false($conn->Execute($query), $query);
		
		
		# INSERT DATA KE TAGIHAN
		$query = "
		INSERT INTO KWT_PEMBAYARAN_AI 
		(
			ID_PEMBAYARAN, TRX, TGL_JATUH_TEMPO, KET_IVC, PERIODE_TAG, PERIODE_AIR, PERIODE_IPL_AWAL, PERIODE_IPL_AKHIR, JUMLAH_PERIODE_IPL, NO_PELANGGAN, KODE_SEKTOR, KODE_CLUSTER, KODE_BLOK, STATUS_BLOK, KODE_ZONA, AKTIF_AIR, AKTIF_IPL, KEY_AIR, KEY_IPL, GOLONGAN, TIPE_DENDA, STAND_LALU, STAND_ANGKAT, STAND_AKHIR, BLOK1, BLOK2, BLOK3, BLOK4, STAND_MIN_PAKAI, TARIF1, TARIF2, TARIF3, TARIF4, TARIF_MIN_PAKAI, LUAS_KAVLING, TARIF_IPL, JUMLAH_AIR, ABONEMEN, JUMLAH_IPL, DENDA, ADM, JUMLAH_BAYAR, DISKON_AIR, TGL_DISKON_AIR, USER_DISKON_AIR, KET_DISKON_AIR, DISKON_IPL, TGL_DISKON_IPL, USER_DISKON_IPL, KET_DISKON_IPL, PERSEN_PPN, NILAI_PPN, STATUS_BAYAR, NO_KWITANSI, BAYAR_VIA, CARA_BAYAR, TGL_BAYAR_BANK, TGL_BAYAR_SYS, USER_BAYAR, KET_BAYAR, STATUS_CETAK_KWT, USER_CETAK_KWT, TGL_CETAK_KWT, STATUS_CETAK_IVC, TGL_CETAK_IVC, USER_CETAK_IVC, STATUS_BATAL, USER_BATAL, TGL_BATAL, KET_BATAL, STATUS_POST_PB, STATUS_POST_BD, NO_FP, TGL_FP, TGL_POST_FP, STATUS_CETAK_FP, TGL_CETAK_FP, USER_CETAK_FP, 
			USER_MODIFIED, 
			MODIFIED_DATE, 
			USER_CREATED
		)
		SELECT 
			ID_PEMBAYARAN, TRX, TGL_JATUH_TEMPO, KET_IVC, PERIODE_TAG, PERIODE_AIR, PERIODE_IPL_AWAL, PERIODE_IPL_AKHIR, JUMLAH_PERIODE_IPL, NO_PELANGGAN, KODE_SEKTOR, KODE_CLUSTER, KODE_BLOK, STATUS_BLOK, KODE_ZONA, AKTIF_AIR, AKTIF_IPL, KEY_AIR, KEY_IPL, GOLONGAN, TIPE_DENDA, STAND_LALU, STAND_ANGKAT, STAND_AKHIR, BLOK1, BLOK2, BLOK3, BLOK4, STAND_MIN_PAKAI, TARIF1, TARIF2, TARIF3, TARIF4, TARIF_MIN_PAKAI, LUAS_KAVLING, TARIF_IPL, JUMLAH_AIR, ABONEMEN, JUMLAH_IPL, DENDA, ADM, JUMLAH_BAYAR, DISKON_AIR, TGL_DISKON_AIR, USER_DISKON_AIR, KET_DISKON_AIR, DISKON_IPL, TGL_DISKON_IPL, USER_DISKON_IPL, KET_DISKON_IPL, PERSEN_PPN, NILAI_PPN, STATUS_BAYAR, NO_KWITANSI, BAYAR_VIA, CARA_BAYAR, TGL_BAYAR_BANK, TGL_BAYAR_SYS, USER_BAYAR, KET_BAYAR, STATUS_CETAK_KWT, USER_CETAK_KWT, TGL_CETAK_KWT, STATUS_CETAK_IVC, TGL_CETAK_IVC, USER_CETAK_IVC, STATUS_BATAL, USER_BATAL, TGL_BATAL, KET_BATAL, STATUS_POST_PB, STATUS_POST_BD, NO_FP, TGL_FP, TGL_POST_FP, STATUS_CETAK_FP, TGL_CETAK_FP, USER_CETAK_FP, 
			NULL AS USER_MODIFIED, 
			NULL AS MODIFIED_DATE, 
			'$sess_id_user' AS USER_CREATED 
		FROM
			KWT_PEMBAYARAN_AI_TEMP 
		WHERE 
			PERIODE_TAG = '$periode_tag' AND 
			ID_PEMBAYARAN NOT IN 
			(
				SELECT ID_PEMBAYARAN FROM KWT_PEMBAYARAN_AI 
				WHERE PERIODE_TAG = '$periode_tag' 
			)
		";
		ex_false($conn->Execute($query), $query);
		
		
		# UPDATE STATUS PROSES DEPOSIT
		$periode_ipl_awal = $conn->Execute("
		SELECT TOP 1 PERIODE_IPL_AWAL 
		FROM KWT_PEMBAYARAN_AI_TEMP 
		WHERE 
			PERIODE_IPL_AWAL IS NOT NULL AND 
			STATUS_BLOK IN ($trx_bg, $trx_rv) 
		")->fields['PERIODE_IPL_AWAL'];
		
		$query = "
		UPDATE d 
		SET d.STATUS_PROSES = 1, 
			d.USER_MODIFIED = '$sess_id_user',
			d.MODIFIED_DATE = GETDATE() 
		FROM 
			KWT_PELANGGAN p
			JOIN KWT_PERIODE_DEPOSIT d ON p.KODE_BLOK = d.KODE_BLOK AND 
				d.STATUS_PROSES = 0 AND 
				d.PERIODE_IPL_AWAL = '$periode_ipl_awal' 
		WHERE
			p.DISABLED = 0 AND 
			p.STATUS_BLOK IN ($trx_bg, $trx_rv) AND 
			p.AKTIF_IPL = 1 
			
			AND p.KODE_BLOK IN (SELECT KODE_BLOK FROM KWT_PEMBAYARAN_AI WHERE PERIODE_TAG = '$periode_tag') 
		";
		ex_false($conn->Execute($query), "Error Update Status Proses Save Deposit, Hubungi Developer/MSI !!");

		$conn->committrans();
		
		$msg = 'Tagihan berhasil diproses.';
		#$msg = $query;
	}
	catch(Exception $e)
	{
		$msg = $e->getmessage();
		$conn->rollbacktrans();
	}

	close($conn);
	$json = array('msg' => $msg);
	echo json_encode($json);
	exit;
}
?>