-- =========================== PEMBAYARAN FA ===========================

-- =========================== PEMBAYARAN PKL ===========================
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_PEMBAYARAN_PKL') AND type in (N'U'))
DROP TABLE KWT_PEMBAYARAN_PKL
GO
CREATE TABLE KWT_PEMBAYARAN_PKL
(
	ID_PEMBAYARAN	INT IDENTITY(1,1) PRIMARY KEY ,
	NO_KTP			VARCHAR (30) ,
	NAMA_PELANGGAN	VARCHAR (40) ,
	NPWP			VARCHAR (25) ,
	ALAMAT			TEXT ,
	NO_TELEPON		VARCHAR (30) ,
	NO_HP			VARCHAR (30) ,
	
	KEY_PKL			VARCHAR (9) ,
	KODE_LOKASI		VARCHAR (6) ,
	KODE_TIPE		VARCHAR (2) ,
	UANG_PANGKAL	NUMERIC (9) DEFAULT 0 ,
	TARIF			NUMERIC (9) DEFAULT 0 ,
	SATUAN			TINYINT,
	LUAS_DURASI		NUMERIC (7, 2) DEFAULT 0 ,
	TGL_SERAHTERIMA	DATE,
	TGL_PEMUTUSAN	DATE,
	KETERANGAN		TEXT,
	
	PERSEN_PPN		NUMERIC (5, 2) DEFAULT 0 ,
	NILAI_PPN		NUMERIC (8) DEFAULT 0 ,
	ADMINISTRASI	NUMERIC (6) DEFAULT 0 ,
	JUMLAH_BAYAR	NUMERIC (10) DEFAULT 0 ,
	
	JENIS_BAYAR 	VARCHAR (1) ,
	KODE_BANK		VARCHAR (3) ,
	NO_REKENING		VARCHAR (40) ,
	NO_TRX			VARCHAR (40) ,
	NO_KWITANSI		VARCHAR (30) ,
	KASIR			VARCHAR (30) ,
	
	STATUS_POS					VARCHAR (1) ,
	NO_FAKTUR_PAJAK				VARCHAR (20) ,
	TGL_FAKTUR_PAJAK			DATETIME2 (0) ,
	TGL_POSTING_FAKTUR_PAJAK	DATETIME2 (0) ,
	
	CREATED_DATE				DATETIME DEFAULT (GETDATE())
)
GO

-- KWT_PEMBAYARAN_PKL NO_KWITANSI
IF OBJECT_ID ('KWT_PEMBAYARAN_PKL_NO_KWITANSI', 'TR') IS NOT NULL
	DROP TRIGGER KWT_PEMBAYARAN_PKL_NO_KWITANSI;
GO
CREATE TRIGGER KWT_PEMBAYARAN_PKL_NO_KWITANSI 
	ON KWT_PEMBAYARAN_PKL
	AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;
	
	UPDATE KWT_PEMBAYARAN_PKL
	SET
		NO_KWITANSI = 
		-- CAST((SELECT MAX(CAST(LEFT(NO_KWITANSI, CASE WHEN CHARINDEX('/', NO_KWITANSI)-1 > 0 THEN CHARINDEX('/', NO_KWITANSI)-1 ELSE 0 END) AS BIGINT)) + 1 FROM KWT_PEMBAYARAN_PKL WHERE NO_KWITANSI IS NOT NULL) AS VARCHAR)
		CAST(ID_PEMBAYARAN AS VARCHAR(100))
		+ '/SYSTEM/KWI/PKL/' 
		+ RIGHT(CONVERT(VARCHAR (10) ,GETDATE() ,103) ,7)
	WHERE
		ID_PEMBAYARAN = (SELECT ID_PEMBAYARAN FROM INSERTED)
END
GO

-- =========================== PEMBAYARAN KSP ===========================
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_PEMBAYARAN_KSP') AND type in (N'U'))
DROP TABLE KWT_PEMBAYARAN_KSP
GO
CREATE TABLE KWT_PEMBAYARAN_KSP
(
	ID_PEMBAYARAN	INT IDENTITY(1,1) PRIMARY KEY ,
	NO_KTP			VARCHAR (30) ,
	NAMA_PELANGGAN	VARCHAR (40) ,
	NPWP			VARCHAR (25) ,
	ALAMAT			TEXT ,
	NO_TELEPON		VARCHAR (30) ,
	NO_HP			VARCHAR (30) ,
	
	KEY_KSP			VARCHAR (9) ,
	KODE_LOKASI		VARCHAR (6) ,
	KODE_TIPE		VARCHAR (2) ,
	SAVE_DEPOSIT	NUMERIC (9) DEFAULT 0 ,
	TARIF			NUMERIC (9) DEFAULT 0 ,
	DURASI			NUMERIC (7, 2) DEFAULT 0 ,
	TGL_SERAHTERIMA	DATE,
	TGL_PEMUTUSAN	DATE,
	KETERANGAN		TEXT,
	
	PERSEN_PPN		NUMERIC (5, 2) DEFAULT 0 ,
	NILAI_PPN		NUMERIC (8) DEFAULT 0 ,
	ADMINISTRASI	NUMERIC (6) DEFAULT 0 ,
	JUMLAH_BAYAR	NUMERIC (10) DEFAULT 0 ,
	
	JENIS_BAYAR 	VARCHAR (1) ,
	KODE_BANK		VARCHAR (3) ,
	NO_REKENING		VARCHAR (40) ,
	NO_TRX			VARCHAR (40) ,
	NO_KWITANSI		VARCHAR (30) ,
	KASIR			VARCHAR (30) ,
	
	STATUS_POS					VARCHAR (1) ,
	NO_FAKTUR_PAJAK				VARCHAR (20) ,
	TGL_FAKTUR_PAJAK			DATETIME2 (0) ,
	TGL_POSTING_FAKTUR_PAJAK	DATETIME2 (0) ,
	
	CREATED_DATE				DATETIME DEFAULT (GETDATE())
)
GO

-- KWT_PEMBAYARAN_KSP NO_KWITANSI
IF OBJECT_ID ('KWT_PEMBAYARAN_KSP_NO_KWITANSI', 'TR') IS NOT NULL
	DROP TRIGGER KWT_PEMBAYARAN_KSP_NO_KWITANSI;
GO
CREATE TRIGGER KWT_PEMBAYARAN_KSP_NO_KWITANSI 
	ON KWT_PEMBAYARAN_KSP
	AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;
	
	UPDATE KWT_PEMBAYARAN_KSP
	SET
		NO_KWITANSI = 
		-- CAST((SELECT MAX(CAST(LEFT(NO_KWITANSI, CASE WHEN CHARINDEX('/', NO_KWITANSI)-1 > 0 THEN CHARINDEX('/', NO_KWITANSI)-1 ELSE 0 END) AS BIGINT)) + 1 FROM KWT_PEMBAYARAN_PKL WHERE NO_KWITANSI IS NOT NULL) AS VARCHAR)
		CAST(ID_PEMBAYARAN AS VARCHAR(100))
		+ '/SYSTEM/KWI/KSP/' 
		+ RIGHT(CONVERT(VARCHAR (10) ,GETDATE() ,103) ,7)
	WHERE
		ID_PEMBAYARAN = (SELECT ID_PEMBAYARAN FROM INSERTED)
END
GO

-- =========================== PEMBAYARAN PSP ===========================
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_PEMBAYARAN_PSP') AND type in (N'U'))
DROP TABLE KWT_PEMBAYARAN_PSP
GO
CREATE TABLE KWT_PEMBAYARAN_PSP
(
	ID_PEMBAYARAN	INT IDENTITY(1,1) PRIMARY KEY ,
	NO_KTP			VARCHAR (30) ,
	NAMA_PELANGGAN	VARCHAR (40) ,
	NPWP			VARCHAR (25) ,
	ALAMAT			TEXT ,
	NO_TELEPON		VARCHAR (30) ,
	NO_HP			VARCHAR (30) ,
	
	KEY_PSP			VARCHAR (9) ,
	KODE_FUNGSI		VARCHAR (6) ,
	KODE_TIPE		VARCHAR (2) ,
	TARIF			NUMERIC (9) DEFAULT 0 ,
	LUAS			NUMERIC (7, 2) DEFAULT 0 ,
	TGL_SERAHTERIMA	DATE,
	TGL_PEMUTUSAN	DATE,
	KETERANGAN		TEXT,
	
	PERSEN_PPN		NUMERIC (5, 2) DEFAULT 0 ,
	NILAI_PPN		NUMERIC (8) DEFAULT 0 ,
	ADMINISTRASI	NUMERIC (6) DEFAULT 0 ,
	JUMLAH_BAYAR	NUMERIC (10) DEFAULT 0 ,
	
	JENIS_BAYAR 	VARCHAR (1) ,
	KODE_BANK		VARCHAR (3) ,
	NO_REKENING		VARCHAR (40) ,
	NO_TRX			VARCHAR (40) ,
	NO_KWITANSI		VARCHAR (30) ,
	KASIR			VARCHAR (30) ,
	
	STATUS_POS					VARCHAR (1) ,
	NO_FAKTUR_PAJAK				VARCHAR (20) ,
	TGL_FAKTUR_PAJAK			DATETIME2 (0) ,
	TGL_POSTING_FAKTUR_PAJAK	DATETIME2 (0) ,
	
	CREATED_DATE				DATETIME DEFAULT (GETDATE())
)
GO

-- KWT_PEMBAYARAN_PSP NO_KWITANSI
IF OBJECT_ID ('KWT_PEMBAYARAN_PSP_NO_KWITANSI', 'TR') IS NOT NULL
	DROP TRIGGER KWT_PEMBAYARAN_PSP_NO_KWITANSI;
GO
CREATE TRIGGER KWT_PEMBAYARAN_PSP_NO_KWITANSI 
	ON KWT_PEMBAYARAN_PSP
	AFTER INSERT
AS
BEGIN
	SET NOCOUNT ON;
	
	UPDATE KWT_PEMBAYARAN_PSP
	SET
		NO_KWITANSI = 
		-- CAST((SELECT MAX(CAST(LEFT(NO_KWITANSI, CASE WHEN CHARINDEX('/', NO_KWITANSI)-1 > 0 THEN CHARINDEX('/', NO_KWITANSI)-1 ELSE 0 END) AS BIGINT)) + 1 FROM KWT_PEMBAYARAN_PKL WHERE NO_KWITANSI IS NOT NULL) AS VARCHAR)
		CAST(ID_PEMBAYARAN AS VARCHAR(100))
		+ '/SYSTEM/KWI/PSP/' 
		+ RIGHT(CONVERT(VARCHAR (10) ,GETDATE() ,103) ,7)
	WHERE
		ID_PEMBAYARAN = (SELECT ID_PEMBAYARAN FROM INSERTED)
END
GO