-- =========================== HELPER ==============================
-- DATETIME2 TO STRING -- CONVERT(VARCHAR (10), [VALUE OR FILED], 105) // DD-MM-YYYY
-- STRING TO DATETIME2 -- CONVERT(DATETIME, [VALUE OR FILED], 105) // DD-MM-YYYY

-- ============================ DROP FK ============================
-- ==== KWT_BLOK ====
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_BLOK_KWT_SEKTOR') AND parent_object_id = OBJECT_ID(N'KWT_BLOK'))
ALTER TABLE KWT_BLOK DROP CONSTRAINT FK_KWT_BLOK_KWT_SEKTOR

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_BLOK_KWT_CLUSTER') AND parent_object_id = OBJECT_ID(N'KWT_BLOK'))
ALTER TABLE KWT_BLOK DROP CONSTRAINT FK_KWT_BLOK_KWT_CLUSTER

-- ==== PKL ====
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_LOKASI_PKL_KWT_SK_SEWA') AND parent_object_id = OBJECT_ID(N'KWT_LOKASI_PKL'))
ALTER TABLE KWT_LOKASI_PKL DROP CONSTRAINT FK_KWT_LOKASI_PKL_KWT_SK_SEWA

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_TARIF_PKL_KWT_LOKASI_PKL') AND parent_object_id = OBJECT_ID(N'KWT_TARIF_PKL'))
ALTER TABLE KWT_TARIF_PKL DROP CONSTRAINT FK_KWT_TARIF_PKL_KWT_LOKASI_PKL
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_TARIF_PKL_KWT_TIPE_PKL') AND parent_object_id = OBJECT_ID(N'KWT_TARIF_PKL'))
ALTER TABLE KWT_TARIF_PKL DROP CONSTRAINT FK_KWT_TARIF_PKL_KWT_TIPE_PKL
GO
-- ==== KSP ====
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_LOKASI_KSP_KWT_SK_SEWA') AND parent_object_id = OBJECT_ID(N'KWT_LOKASI_KSP'))
ALTER TABLE KWT_LOKASI_KSP DROP CONSTRAINT FK_KWT_LOKASI_KSP_KWT_SK_SEWA

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_TARIF_KSP_KWT_LOKASI_KSP') AND parent_object_id = OBJECT_ID(N'KWT_TARIF_KSP'))
ALTER TABLE KWT_TARIF_KSP DROP CONSTRAINT FK_KWT_TARIF_KSP_KWT_LOKASI_KSP
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_TARIF_KSP_KWT_TIPE_KSP') AND parent_object_id = OBJECT_ID(N'KWT_TARIF_KSP'))
ALTER TABLE KWT_TARIF_KSP DROP CONSTRAINT FK_KWT_TARIF_KSP_KWT_TIPE_KSP
GO

-- ==== MP ====
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_TARIF_MPD_KWT_LOKASI_MP') AND parent_object_id = OBJECT_ID(N'KWT_TARIF_MPD'))
ALTER TABLE KWT_TARIF_MPD DROP CONSTRAINT FK_KWT_TARIF_MPD_KWT_LOKASI_MP
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_TARIF_MPD_KWT_TARIF_MP') AND parent_object_id = OBJECT_ID(N'KWT_TARIF_MPD'))
ALTER TABLE KWT_TARIF_MPD DROP CONSTRAINT FK_KWT_TARIF_MPD_KWT_TARIF_MP
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_TARIF_MP_KWT_SK_SEWA') AND parent_object_id = OBJECT_ID(N'KWT_TARIF_MP'))
ALTER TABLE KWT_TARIF_MP DROP CONSTRAINT FK_KWT_TARIF_MP_KWT_SK_SEWA
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_TARIF_MP_KWT_TIPE_MP') AND parent_object_id = OBJECT_ID(N'KWT_TARIF_MP'))
ALTER TABLE KWT_TARIF_MP DROP CONSTRAINT FK_KWT_TARIF_MP_KWT_TIPE_MP
GO

-- ==== PSP ====
IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_TARIF_PSP_KWT_SK_PSP') AND parent_object_id = OBJECT_ID(N'KWT_TARIF_PSP'))
ALTER TABLE KWT_TARIF_PSP DROP CONSTRAINT FK_KWT_TARIF_PSP_KWT_SK_PSP
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_TARIF_PSP_KWT_TIPE_PSP') AND parent_object_id = OBJECT_ID(N'KWT_TARIF_PSP'))
ALTER TABLE KWT_TARIF_PSP DROP CONSTRAINT FK_KWT_TARIF_PSP_KWT_TIPE_PSP
GO

IF EXISTS (SELECT * FROM sys.foreign_keys WHERE object_id = OBJECT_ID(N'FK_KWT_TARIF_PSP_KWT_FUNGSI_PSP') AND parent_object_id = OBJECT_ID(N'KWT_TARIF_PSP'))
ALTER TABLE KWT_TARIF_PSP DROP CONSTRAINT FK_KWT_TARIF_PSP_KWT_FUNGSI_PSP
GO

-- KWT_USER
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_USER') AND type in (N'U'))
DROP TABLE KWT_USER
GO
CREATE TABLE KWT_USER 
(
	ID_USER VARCHAR (100) PRIMARY KEY ,
	NAMA_USER VARCHAR (100) ,
	PASS_USER VARCHAR (100) ,
	AKTIF_USER VARCHAR (1) -- (0 = TIDAK) (1 = YA)
)
GO

-- KWT_USER_MODUL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_USER_MODUL') AND type in (N'U'))
DROP TABLE KWT_USER_MODUL
GO
CREATE TABLE KWT_USER_MODUL 
(
	ID_USER VARCHAR (100) ,
	ID_MODUL VARCHAR (100)
)
GO

-- KWT_PARAMETER
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_PARAMETER') AND type in (N'U'))
DROP TABLE KWT_PARAMETER
GO
CREATE TABLE KWT_PARAMETER 
(
	-- JRP
	JRP_PT VARCHAR (100) ,			JRP_KODE_POS VARCHAR (5) ,
	JRP_ALAMAT_1 VARCHAR (200) ,	JRP_TELP VARCHAR (30) ,
	JRP_ALAMAT_2 VARCHAR (200) ,	JRP_FAX VARCHAR (30) ,
	JRP_KOTA VARCHAR (100) ,		JRP_EMAIL VARCHAR (30) ,
	
	-- UNIT
	UNIT_NAMA VARCHAR (100) ,		UNIT_KODE_POS VARCHAR (5) ,
	UNIT_ALAMAT_1 VARCHAR (200) ,	UNIT_TELP VARCHAR (30) ,
	UNIT_ALAMAT_2 VARCHAR (200) ,	UNIT_FAX VARCHAR (30) ,
	UNIT_KOTA VARCHAR (100) ,		UNIT_EMAIL VARCHAR (30) ,
	
	-- GLOBAL
	---JABATAN
	NAMA_PIMPINAN VARCHAR (100),		JBT_PIMPINAN VARCHAR (100), 
	NAMA_PAJAK VARCHAR (100),			JBT_PAJAK VARCHAR (100), 
	NAMA_ADMINISTRASI VARCHAR (100),	JBT_ADMINISTRASI VARCHAR (100), 
	
	---REG
	COU_NP NUMERIC (7) DEFAULT 0 ,
	REG_NPWP VARCHAR (30) ,
	PERSEN_PPN NUMERIC (5, 2) DEFAULT 0 ,
	REG_FP VARCHAR (15) ,
	COU_FP NUMERIC (8) DEFAULT 0 ,
	
	-- KAVLING KOSONG
	ADMINISTRASI_KV NUMERIC (6) DEFAULT 0 ,
	REG_IVC_KV VARCHAR (30) ,
	COU_IVC_KV NUMERIC (7) DEFAULT 0 ,
	REG_KWT_KV VARCHAR (30) ,
	COU_KWT_KV NUMERIC (7) DEFAULT 0 ,
	BANER_KV VARCHAR (100) ,
	
	-- MASA MEMBANGUN
	--- IPL
	ADMINISTRASI_BG NUMERIC (6) DEFAULT 0 ,
	REG_IVC_BG VARCHAR (30) ,
	COU_IVC_BG NUMERIC (7) DEFAULT 0 ,
	REG_KWT_BG VARCHAR (30) ,
	COU_KWT_BG NUMERIC (7) DEFAULT 0 ,
	BANER_BG VARCHAR (100) ,
	
	--- DEPOSIT
	ADMINISTRASI_DB NUMERIC (6) DEFAULT 0 ,
	REG_IVC_DB VARCHAR (30) ,
	COU_IVC_DB NUMERIC (7) DEFAULT 0 ,
	REG_KWT_DB VARCHAR (30) ,
	COU_KWT_DB NUMERIC (7) DEFAULT 0 ,
	BANER_DB VARCHAR (100) ,
	
	-- HUNIAN
	ADMINISTRASI_HN NUMERIC (6) DEFAULT 0 ,
	REG_IVC_HN VARCHAR (30) ,
	COU_IVC_HN NUMERIC (7) DEFAULT 0 ,
	REG_KWT_HN VARCHAR (30) ,
	COU_KWT_HN NUMERIC (7) DEFAULT 0 ,
	BANER_HN VARCHAR (100) ,

	-- RENOVASI
	--- IPL
	ADMINISTRASI_RV NUMERIC (6) DEFAULT 0 ,
	REG_IVC_RV VARCHAR (30) ,
	COU_IVC_RV NUMERIC (7) DEFAULT 0 ,
	REG_KWT_RV VARCHAR (30) ,
	COU_KWT_RV NUMERIC (7) DEFAULT 0 ,
	BANER_RV VARCHAR (100) ,
	
	--- DEPOSIT
	ADMINISTRASI_DR NUMERIC (6) DEFAULT 0 , 
	REG_IVC_DR VARCHAR (30) ,
	COU_IVC_DR NUMERIC (7) DEFAULT 0 , 
	REG_KWT_DR VARCHAR (30) ,
	COU_KWT_DR NUMERIC (7) DEFAULT 0 , 
	BANER_DR VARCHAR (100) ,	
)
GO

-- KWT_BANK
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_BANK') AND type in (N'U'))
DROP TABLE KWT_BANK
GO
CREATE TABLE KWT_BANK 
(
	KODE_BANK VARCHAR (3) PRIMARY KEY ,
	NAMA_BANK VARCHAR (40) ,
	CB_BANK VARCHAR (30) ,
	ALAMAT TEXT
)
GO

-- KWT_SEKTOR
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_SEKTOR') AND type in (N'U'))
DROP TABLE KWT_SEKTOR
GO
CREATE TABLE KWT_SEKTOR 
(
	KODE_SEKTOR VARCHAR (6) PRIMARY KEY ,
	NAMA_SEKTOR VARCHAR (40) ,
	KODE_PEL VARCHAR (2)
)
GO

-- KWT_CLUSTER
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_CLUSTER') AND type in (N'U'))
DROP TABLE KWT_CLUSTER
GO
CREATE TABLE KWT_CLUSTER 
(
	KODE_CLUSTER VARCHAR (3) PRIMARY KEY ,
	KODE_SEKTOR VARCHAR (6) ,
	NAMA_CLUSTER VARCHAR (40) 
)
GO

-- KWT_BLOK
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_BLOK') AND type in (N'U'))
DROP TABLE KWT_BLOK
GO
CREATE TABLE KWT_BLOK 
(
	KODE_BLOK VARCHAR (15) PRIMARY KEY , 
	KODE_SEKTOR VARCHAR (6) , 
	KODE_CLUSTER VARCHAR (3) , 
	LUAS_KAVLING NUMERIC (9, 2) DEFAULT 0 , 
	LUAS_BANGUNAN NUMERIC (9, 2) DEFAULT 0 , 
	STATUS_BLOK VARCHAR (1) NOT NULL , 
		-- 1 = KAVLING KOSONG
		-- 2 = MASA MEMBANGUN
		-- 4 = HUNIA
		-- 5 = RENOVASI
)
GO

-- KWT_CLUSTER
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_CLUSTER') AND type in (N'U'))
DROP TABLE KWT_CLUSTER
GO
CREATE TABLE KWT_CLUSTER 
(
	KODE_CLUSTER VARCHAR (3) PRIMARY KEY ,
	KODE_SEKTOR VARCHAR (6) ,
	NAMA_CLUSTER VARCHAR (40) 
)
GO

-- KWT_SK_AIR
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_SK_AIR') AND type in (N'U'))
DROP TABLE KWT_SK_AIR
GO
CREATE TABLE KWT_SK_AIR 
(
	KODE_SK VARCHAR (3) PRIMARY KEY ,
	NO_SK VARCHAR (30) ,
	TGL_SK DATE , 
	TGL_BERLAKU DATE , 
	PEMBUAT VARCHAR (30) ,
	STATUS_SK VARCHAR (1) DEFAULT '0', 
	KETERANGAN TEXT
)
GO 

-- KWT_TIPE_AIR
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TIPE_AIR') AND type in (N'U'))
DROP TABLE KWT_TIPE_AIR
GO
CREATE TABLE KWT_TIPE_AIR 
(
	KODE_TIPE VARCHAR (2) PRIMARY KEY ,
	NAMA_TIPE VARCHAR (30) ,
	PERSEN_ASUMSI_1 NUMERIC (6, 2) DEFAULT 0 ,
	PERSEN_ASUMSI_2 NUMERIC (6, 2) DEFAULT 0 ,
	PERSEN_ASUMSI_3 NUMERIC (6, 2) DEFAULT 0 ,
	PERSEN_ASUMSI_4 NUMERIC (6, 2) DEFAULT 0 ,
	GOLONGAN VARCHAR (1) DEFAULT '0'			-- UNTUK PROSES DENDA (0 = STANDAR) (1 = BISNIS)
)
GO 

-- KWT_TARIF_AIR
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TARIF_AIR') AND type in (N'U'))
DROP TABLE KWT_TARIF_AIR
GO
CREATE TABLE KWT_TARIF_AIR 
(
	KEY_AIR VARCHAR (8) PRIMARY KEY ,
	KODE_SK VARCHAR (3) ,
	KODE_TIPE VARCHAR (2) ,
	ABONEMEN NUMERIC (6) DEFAULT 0 ,
	STAND_MIN_PAKAI INT DEFAULT 0,
	BLOK1 NUMERIC (5) DEFAULT 0 ,
	BLOK2 NUMERIC (5) DEFAULT 0 ,
	BLOK3 NUMERIC (5) DEFAULT 0 ,
	BLOK4 NUMERIC (5) DEFAULT 0 ,
	TARIF1 NUMERIC (8) DEFAULT 0 ,
	TARIF2 NUMERIC (8) DEFAULT 0 ,
	TARIF3 NUMERIC (8) DEFAULT 0 ,
	TARIF4 NUMERIC (8) DEFAULT 0 ,
	DENDA_BISNIS_AIR NUMERIC (5, 2) DEFAULT 0 ,
	DENDA_STANDAR_AIR NUMERIC (5, 2) DEFAULT 0 ,
	KETERANGAN TEXT
)
GO

-- KWT_SK_IPL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_SK_IPL') AND type in (N'U'))
DROP TABLE KWT_SK_IPL
GO
CREATE TABLE KWT_SK_IPL 
(
	KODE_SK VARCHAR (3) PRIMARY KEY ,
	NO_SK VARCHAR (30) ,
	TGL_SK DATE , 
	TGL_BERLAKU DATE , 
	PEMBUAT VARCHAR (30) ,
	STATUS_SK VARCHAR (1) DEFAULT '0', 
	KETERANGAN TEXT
)
GO 

-- KWT_TIPE_IPL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TIPE_IPL') AND type in (N'U'))
DROP TABLE KWT_TIPE_IPL
GO
CREATE TABLE KWT_TIPE_IPL 
(
	KODE_TIPE VARCHAR (9) PRIMARY KEY ,
	NAMA_TIPE VARCHAR (100) ,
	GOLONGAN VARCHAR (1) DEFAULT '0',		-- UNTUK PROSES DENDA (0 = STANDAR) (1 = BISNIS)
	STATUS_BLOK VARCHAR (1) NOT NULL ,
		-- 1 = KAVLING KOSONG
		-- 2 = MASA MEMBANGUN
		-- 4 = HUNIA
		-- 5 = RENOVASI
)
GO 

-- KWT_TARIF_IPL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TARIF_IPL') AND type in (N'U'))
DROP TABLE KWT_TARIF_IPL
GO
CREATE TABLE KWT_TARIF_IPL 
(
	KEY_IPL VARCHAR (15) PRIMARY KEY ,
	KODE_SK VARCHAR (3) ,
	KODE_TIPE VARCHAR (9) ,
	TIPE_TARIF_IPL VARCHAR (1) DEFAULT '0',		-- TIPE_TARIF (0 = TETAP) (1 = PER METER)
	TARIF_IPL NUMERIC (8) DEFAULT 0 ,
	DENDA_STANDAR_IPL NUMERIC (5, 2) DEFAULT 0 ,
	DENDA_BISNIS_IPL NUMERIC (5, 2) DEFAULT 0 ,
	NILAI_DEPOSIT NUMERIC (15) DEFAULT 0 ,
	KETERANGAN TEXT
)
GO

-- KWT_ZONA_METER_BALANCE
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_ZONA_METER_BALANCE') AND type in (N'U'))
DROP TABLE KWT_ZONA_METER_BALANCE
GO
CREATE TABLE KWT_ZONA_METER_BALANCE 
(
	KODE_ZONA VARCHAR (3) PRIMARY KEY ,
	NAMA_ZONA VARCHAR (30) 
)
GO

-- KWT_DISKON_KHUSUS
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_DISKON_KHUSUS') AND type in (N'U'))
DROP TABLE KWT_DISKON_KHUSUS
GO
CREATE TABLE KWT_DISKON_KHUSUS 
(
	ID_DISKON INT NOT NULL IDENTITY(1,1) PRIMARY KEY ,	-- Penambahan (Untuk Proses Edit)
	KODE_BLOK VARCHAR (15) ,
	PERIODE_AWAL VARCHAR (6) ,
	PERIODE_AKHIR VARCHAR (6) ,
	DISKON_AIR_NILAI NUMERIC (12, 2) DEFAULT 0 ,
	DISKON_IPL_NILAI NUMERIC (12, 2) DEFAULT 0 ,
	DISKON_AIR_PERSEN NUMERIC (5, 2) DEFAULT 0 ,
	DISKON_IPL_PERSEN NUMERIC (5, 2) DEFAULT 0 ,
	KETERANGAN TEXT 
)
GO

-- KWT_PELANGGAN_LOOKUP
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_PELANGGAN_LOOKUP') AND type in (N'U'))
DROP TABLE KWT_PELANGGAN_LOOKUP
GO
CREATE TABLE KWT_PELANGGAN_LOOKUP
(
	NO_KTP			VARCHAR (30) PRIMARY KEY ,
	NAMA_PELANGGAN	VARCHAR (40) ,
	NPWP			VARCHAR (25) ,
	ALAMAT			TEXT ,
	NO_TELEPON		VARCHAR (30) ,
	NO_HP			VARCHAR (30) ,
	KODE_BANK		VARCHAR (3) ,
	NO_REKENING		VARCHAR (40)
)
GO

-- KWT_PELANGGAN 
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_PELANGGAN') AND type in (N'U'))
DROP TABLE KWT_PELANGGAN
GO
CREATE TABLE KWT_PELANGGAN 
(
	NO_PELANGGAN VARCHAR (15) PRIMARY KEY ,
	TGL_PPJB DATE ,
	INFO_TAGIHAN VARCHAR (1) , -- (NULL = TIDAK) (1 = YA) 
	
	KODE_SEKTOR VARCHAR (6) ,
	KODE_CLUSTER VARCHAR (3) ,
	KODE_BLOK VARCHAR (30) ,
	LUAS_KAVLING NUMERIC (9, 2) DEFAULT 0 ,
	LUAS_BANGUNAN NUMERIC (9, 2) DEFAULT 0 ,
	STATUS_BLOK VARCHAR (1) NOT NULL ,
		-- 1 = KAVLING KOSONG
		-- 2 = MASA MEMBANGUN
		-- 4 = HUNIA
		-- 5 = RENOVASI
	
	NAMA_PELANGGAN VARCHAR (40) ,
	NO_KTP VARCHAR (30) ,
	NPWP VARCHAR (25) ,
	ALAMAT TEXT ,
	NO_TELEPON VARCHAR (30) ,
	NO_HP VARCHAR (20) ,
	
	PAKAI_SM VARCHAR (1) ,
	SM_NAMA_PELANGGAN VARCHAR (40) ,
	SM_ALAMAT TEXT ,
	SM_NO_TELEPON VARCHAR (30) ,
	SM_NO_HP VARCHAR (20) ,
	
	-- PEMBAYARAN
	DEBET_BANK VARCHAR (1) , -- (NULL = TIDAK) (1 = YA) 
	KODE_BANK VARCHAR (3) , 
	NO_REKENING VARCHAR (40) , 
	
	-- AIR
	AKTIF_AIR VARCHAR (1) , -- (NULL = TIDAK) (1 = YA) 
	KODE_ZONA VARCHAR (3) ,
	TIPE_AIR VARCHAR (2) ,
	KEY_AIR VARCHAR (8) ,
	
	TGL_PEMUTUSAN DATE ,
	PETUGAS VARCHAR (50) ,
	PERIODE_PUTUS VARCHAR (6) ,
	
	-- IPL
	AKTIF_IPL VARCHAR (1) , -- (NULL = TIDAK) (1 = YA) 
	TIPE_IPL VARCHAR (9) ,
	KEY_IPL VARCHAR (15) ,
	
	KETERANGAN TEXT ,
	
	STATUS_JOIN VARCHAR (1), -- (NULL = TIDAK) (1 = YA) 
	JOIN_TO VARCHAR (30) ,
	USER_JOIN VARCHAR (50) ,
	JOIN_DATE DATETIME2 (0) ,
	
	STATUS_SPLIT VARCHAR (1), -- (NULL = TIDAK) (1 = YA) 
	SPLIT_FROM VARCHAR (30) ,
	USER_SPLIT VARCHAR (50) ,
	SPLIT_DATE DATETIME2 (0) ,
	
	DISABLED VARCHAR (1), -- (NULL = TIDAK) (1 = YA) 
	
	CREATED_DATE DATETIME2 (0) DEFAULT GETDATE()
)
GO 

-- KWT_PELANGGAN_IMP
--===============================
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_PELANGGAN_IMP') AND type in (N'U'))
DROP TABLE KWT_PELANGGAN_IMP
GO
SELECT * INTO KWT_PELANGGAN_IMP FROM KWT_PELANGGAN WHERE 1=0
GO
ALTER TABLE KWT_PELANGGAN_IMP ADD STATUS_PROSES VARCHAR(1)
GO
ALTER TABLE KWT_PELANGGAN_IMP ADD PRIMARY KEY (NO_PELANGGAN)
GO

-- KWT_PEMBAYARAN_AI_DEL
--===============================
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_PEMBAYARAN_AI_DEL') AND type in (N'U'))
DROP TABLE KWT_PEMBAYARAN_AI_DEL
GO
SELECT * INTO KWT_PEMBAYARAN_AI_DEL FROM KWT_PEMBAYARAN_AI WHERE 1=0
GO
ALTER TABLE KWT_PEMBAYARAN_AI_DEL
ADD 
	USER_DEL VARCHAR(50), 
	KETERANGAN_DEL TEXT,
	TGL_DEL DATETIME2(0) DEFAULT GETDATE()
GO

-- KWT_PEMUTUSAN_AIR
--===============================
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_PEMUTUSAN_AIR') AND type in (N'U'))
DROP TABLE KWT_PEMUTUSAN_AIR
GO
CREATE TABLE KWT_PEMUTUSAN_AIR
(
	NO_PELANGGAN VARCHAR (15) ,
	PERIODE_PUTUS VARCHAR (6) ,
	TGL_PEMUTUSAN DATE ,
	USER_PUTUS VARCHAR (50) ,
	CREATED_DATE DATETIME2 (0) DEFAULT GETDATE()
)
GO
--=============================== MASA MEMBANGUN ===============================
-- KWT_PERIODE_DEPOSIT
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_PERIODE_DEPOSIT') AND type in (N'U'))
DROP TABLE KWT_PERIODE_DEPOSIT
GO
CREATE TABLE KWT_PERIODE_DEPOSIT
(
	ID_DEPOSIT VARCHAR (100) PRIMARY KEY , 	-- TRX#PERIODE_AWAL#KODE_BLOK
	TRX VARCHAR (1) NOT NULL ,
		-- 3 = MASA MEMBANGUN (DEPOSIT)
		-- 6 = RENOVASI (DEPOSIT)
		
	KODE_BLOK VARCHAR (15) ,
	
	PERIODE_AWAL VARCHAR (6) ,
	PERIODE_AKHIR VARCHAR (6) ,
	JUMLAH_PERIODE INT DEFAULT 1 ,
	NILAI_DEPOSIT NUMERIC (15) DEFAULT 0 ,
	KETERANGAN TEXT ,
	
	STATUS_PROSES VARCHAR (1) ,						-- (NULL = BELUM) (1 = SUDAH) 
	
	STATUS_EDIT VARCHAR (1) ,						-- (NULL = BELUM) (1 = SUDAH) 
	USER_EDIT VARCHAR (50) ,
	TGL_EDIT DATETIME2 (0) ,
	
	CREATED_DATE DATETIME2 (0) DEFAULT GETDATE()
)
GO

--============================================== PEMBAYARAN ==========================================
-- KWT_PEMBAYARAN_AI
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_PEMBAYARAN_AI') AND type in (N'U'))
DROP TABLE KWT_PEMBAYARAN_AI
GO
CREATE TABLE KWT_PEMBAYARAN_AI(
	ID_PEMBAYARAN VARCHAR (100) PRIMARY KEY ,	-- TRX#PERIODE#NO_PELANGGAN
	TRX VARCHAR (1) NOT NULL ,
		-- 1 = KAVLING KOSONG (AIR & IPL) 
		-- 2 = MASA MEMBANGUN (AIR & IPL)
		-- 3 = MASA MEMBANGUN (DEPOSIT)
		-- 4 = HUNIA (AIR & IPL)
		-- 5 = RENOVASI (AIR & IPL)
		-- 6 = RENOVASI (DEPOSIT)
	NO_INVOICE VARCHAR (50) ,
	
	-- PERIODE
	PERIODE VARCHAR (6) ,
	PERIODE_AWAL VARCHAR (6) ,
	PERIODE_AKHIR VARCHAR (6) ,
	JUMLAH_PERIODE INT,
	
	NO_PELANGGAN VARCHAR (15) ,
	
	KODE_SEKTOR VARCHAR (6) ,
	KODE_CLUSTER VARCHAR (3) ,
	KODE_BLOK VARCHAR (15) ,
	STATUS_BLOK VARCHAR (1) NOT NULL ,
		-- 1 = KAVLING KOSONG
		-- 2 = MASA MEMBANGUN
		-- 4 = HUNIA
		-- 5 = RENOVASI
	KODE_ZONA VARCHAR (3) ,
	
	AKTIF_AIR VARCHAR (1) , -- (NULL = TIDAK) (1 = YA) 
	AKTIF_IPL VARCHAR (1) , -- (NULL = TIDAK) (1 = YA) 
	
	KEY_AIR VARCHAR (8) ,
	KEY_IPL VARCHAR (15) ,
	
	-- PERHITUNGAN AIR
	STAND_LALU NUMERIC (10) DEFAULT 0 ,
	STAND_ANGKAT NUMERIC (10) DEFAULT 0 ,
	STAND_AKHIR NUMERIC (10) DEFAULT 0 ,
	
	BLOK1 NUMERIC (5) DEFAULT 0 ,
	BLOK2 NUMERIC (5) DEFAULT 0 ,
	BLOK3 NUMERIC (5) DEFAULT 0 ,
	BLOK4 NUMERIC (5) DEFAULT 0 ,
	STAND_MIN_PAKAI NUMERIC (3) DEFAULT 0 ,
	TARIF1 NUMERIC (8) DEFAULT 0 ,
	TARIF2 NUMERIC (8) DEFAULT 0 ,
	TARIF3 NUMERIC (8) DEFAULT 0 ,
	TARIF4 NUMERIC (8) DEFAULT 0 ,
	TARIF_MIN_PAKAI NUMERIC (10) DEFAULT 0 ,
	
	-- PERHITUNGAN IPL 
	LUAS_KAVLING NUMERIC (9, 2) DEFAULT 0 ,
	TARIF_IPL NUMERIC (8) DEFAULT 0 ,
	
	JUMLAH_AIR NUMERIC (10) DEFAULT 0 ,
	ABONEMEN NUMERIC (6) DEFAULT 0 ,
	JUMLAH_IPL NUMERIC (10) DEFAULT 0 ,
	DENDA NUMERIC (10) DEFAULT 0 ,
	ADMINISTRASI NUMERIC (6) DEFAULT 0 ,
	JUMLAH_BAYAR NUMERIC (10) DEFAULT 0 ,
	
	DISKON_PERSEN_AIR NUMERIC (7, 3) DEFAULT 0 ,
	DISKON_RUPIAH_AIR NUMERIC (10) DEFAULT 0 ,
	TGL_DISKON_AIR DATETIME2 (0) ,
	USER_DISKON_AIR VARCHAR (50) ,
	
	DISKON_PERSEN_IPL NUMERIC (7, 3) DEFAULT 0 ,
	DISKON_RUPIAH_IPL NUMERIC (10) DEFAULT 0 ,
	TGL_DISKON_IPL DATETIME2 (0) ,
	USER_DISKON_IPL VARCHAR (50) ,
	
	KETERANGAN_DISKON TEXT ,
	
	PERSEN_PPN NUMERIC (5, 2) DEFAULT 0 ,
	NILAI_PPN NUMERIC (8) DEFAULT 0 ,
	
	STATUS_BAYAR VARCHAR (1) ,		-- (NULL = BELUM) (2 = SUDAH) 
	NO_KWITANSI VARCHAR (50) ,
	BAYAR_MELALUI VARCHAR (3) ,
	JENIS_BAYAR VARCHAR (1) ,
		-- (NULL = BELUM) 
		-- (1 = TUNAI)
		-- (2 = K. DEBIT)
		-- (3 = K. KREDIT)
		-- (4 = T. BANK)
	TGL_BAYAR DATETIME2 (0) ,
	TGL_TERIMA_BANK DATETIME2 (0) ,
	KASIR VARCHAR (30) ,
	KETERANGAN_BAYAR TEXT,
	
	STATUS_CETAK_KWT VARCHAR (1) ,	-- (NULL = BELUM) (1 = SUDAH) 
	STATUS_CETAK_IVC VARCHAR (1) ,	-- (NULL = BELUM) (1 = SUDAH) 
	
	NO_FAKTUR_PAJAK VARCHAR (40) ,
	TGL_FAKTUR_PAJAK DATE ,
	TGL_POST_FP DATE ,
	
	STATUS_POST_PB VARCHAR (1) ,	-- (NULL = BELUM) (1 = SUDAH) 
	
	STATUS_EDIT VARCHAR (1) ,		-- (NULL = BELUM) (1 = SUDAH) 
	USER_EDIT VARCHAR (50) ,
	TGL_EDIT DATETIME2 (0) ,
	
	STATUS_BATAL VARCHAR (1) ,		-- (NULL = BELUM) (1 = SUDAH) 
	USER_BATAL VARCHAR (50) ,
	TGL_BATAL DATETIME2 (0) ,
	KETERANGAN_BATAL TEXT,
)
GO

-- KWT_POST_PEMBAYARAN
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_POST_PEMBAYARAN') AND type in (N'U'))
DROP TABLE KWT_POST_PEMBAYARAN
GO
CREATE TABLE KWT_POST_PEMBAYARAN 
(
	TRX VARCHAR (1) ,
	USER_POST VARCHAR (50) ,
	TGL_POST DATE
)
GO 

-- KWT_POST_FAKTUR_PAJAK
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_POST_FAKTUR_PAJAK') AND type in (N'U'))
DROP TABLE KWT_POST_FAKTUR_PAJAK
GO
CREATE TABLE KWT_POST_FAKTUR_PAJAK 
(
	USER_POST VARCHAR (50) ,
	TGL_POST DATE
)
GO 

-- ============================ FASILITAS ===============================-- 
-- KWT_SK_SEWA (SK SEWA)
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_SK_SEWA') AND type in (N'U'))
DROP TABLE KWT_SK_SEWA
GO
CREATE TABLE KWT_SK_SEWA
(
	KODE_SK VARCHAR (3) PRIMARY KEY ,
	NO_SK VARCHAR (50) ,
	TGL_SK DATE , 
	TGL_BERLAKU DATE , 
	PEMBUAT VARCHAR (50) ,
	STATUS_SK VARCHAR (1) DEFAULT '0', 
	KETERANGAN TEXT
)
GO 

-- ============================ PEDAGANG KAKILIMA (PKL) ===============================-- 
-- KWT_LOKASI_PKL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_LOKASI_PKL') AND type in (N'U'))
DROP TABLE KWT_LOKASI_PKL
GO
CREATE TABLE KWT_LOKASI_PKL 
(
	KODE_LOKASI VARCHAR (6) PRIMARY KEY ,
	KODE_SK VARCHAR (3) ,
	NAMA_LOKASI VARCHAR (50) ,
	DETAIL_LOKASI TEXT
)
GO 

-- KWT_TIPE_PKL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TIPE_PKL') AND type in (N'U'))
DROP TABLE KWT_TIPE_PKL
GO
CREATE TABLE KWT_TIPE_PKL 
(
	KODE_TIPE VARCHAR (2) PRIMARY KEY ,
	NAMA_TIPE VARCHAR (50)
)
GO 

-- KWT_TARIF_PKL
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TARIF_PKL') AND type in (N'U'))
DROP TABLE KWT_TARIF_PKL
GO
CREATE TABLE KWT_TARIF_PKL 
(
	KEY_PKL VARCHAR (9) PRIMARY KEY ,
	KODE_LOKASI VARCHAR (6) ,
	KODE_TIPE VARCHAR (2) ,
	UANG_PANGKAL NUMERIC (9) DEFAULT 0 ,
	TARIF NUMERIC (9) DEFAULT 0 ,
	SATUAN VARCHAR (1) DEFAULT '1' -- (0 = M2) (1 = BLN)
)
GO

-- ============================ KEGIATAN SHOOTING/PEMOTRETAN (KSP) ===============================-- 
-- KWT_LOKASI_KSP
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_LOKASI_KSP') AND type in (N'U'))
DROP TABLE KWT_LOKASI_KSP
GO
CREATE TABLE KWT_LOKASI_KSP 
(
	KODE_LOKASI VARCHAR (6) PRIMARY KEY ,
	KODE_SK VARCHAR (3) ,
	TIPE_LOKASI VARCHAR (2) ,		-- ('ID' = INDOOR) ('OD' = OUTDOOR)
	DETAIL_LOKASI TEXT ,
)
GO 

-- KWT_TIPE_KSP
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TIPE_KSP') AND type in (N'U'))
DROP TABLE KWT_TIPE_KSP
GO
CREATE TABLE KWT_TIPE_KSP 
(
	KODE_TIPE VARCHAR (2) PRIMARY KEY ,
	NAMA_TIPE VARCHAR (50)
)
GO 

-- KWT_TARIF_KSP
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TARIF_KSP') AND type in (N'U'))
DROP TABLE KWT_TARIF_KSP
GO
CREATE TABLE KWT_TARIF_KSP 
(
	KEY_KSP VARCHAR (9) PRIMARY KEY ,
	KODE_LOKASI VARCHAR (6) ,
	KODE_TIPE VARCHAR (2) ,
	SAVE_DEPOSIT NUMERIC (9) DEFAULT 0 ,
	TARIF NUMERIC (9) DEFAULT 0	
)
GO

-- ============================ MEDIA PROMO (MP) ===============================-- 
-- KWT_TIPE_MP
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TIPE_MP') AND type in (N'U'))
DROP TABLE KWT_TIPE_MP
GO
CREATE TABLE KWT_TIPE_MP 
(
	KODE_TIPE VARCHAR (3) PRIMARY KEY ,
	KODE_MP VARCHAR (1) ,
	NAMA_TIPE VARCHAR (50)
	-- KODE_MP
	-- A = BILLBOARD / SIGNBOARD / PYLON SIGN
	-- B = NEON BOX / NEON SIGN
	-- C = SPANDUK / UMBUL-UMBUL / STANDING DISPLAY
	-- D = BANNER / BALIHO
	-- E = BUS TRANS BINTARO JAYA
	-- F = HALTE BUS BINTARO JAYA DAN TRANS BINTARO JAYA
)
GO 

-- KWT_LOKASI_MP
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_LOKASI_MP') AND type in (N'U'))
DROP TABLE KWT_LOKASI_MP
GO
CREATE TABLE KWT_LOKASI_MP 
(
	KODE_LOKASI VARCHAR (2) PRIMARY KEY ,
	NAMA_LOKASI VARCHAR (50)
)
GO 

-- KWT_TARIF_MP
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TARIF_MP') AND type in (N'U'))
DROP TABLE KWT_TARIF_MP
GO
CREATE TABLE KWT_TARIF_MP 
(
	KEY_MP VARCHAR (7) PRIMARY KEY ,
	KODE_SK VARCHAR (3) ,
	KODE_TIPE VARCHAR (3) ,
	KODE_MP VARCHAR (1) ,
	UKURAN_1 VARCHAR (10) , -- UNTUK KODE_MP A-D
	UKURAN_2 VARCHAR (10) , -- UNTUK KODE_MP A-C
	TARIF NUMERIC (9) DEFAULT 0 ,	-- UNTUK KODE_MP E & F
	KETERANGAN TEXT
	
	-- KODE_MP
	-- A = BILLBOARD / SIGNBOARD / PYLON SIGN
	-- B = NEON BOX / NEON SIGN
	-- C = SPANDUK / UMBUL-UMBUL / STANDING DISPLAY
	-- D = BANNER / BALIHO
	-- E = BUS TRANS BINTARO JAYA
	-- F = HALTE BUS BINTARO JAYA DAN TRANS BINTARO JAYA
)
GO

-- KWT_TARIF_MPD
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TARIF_MPD') AND type in (N'U'))
DROP TABLE KWT_TARIF_MPD
GO
CREATE TABLE KWT_TARIF_MPD 
(
	KEY_MPD VARCHAR (10) PRIMARY KEY ,
	KEY_MP VARCHAR (7) ,
	KODE_LOKASI VARCHAR (2) ,
	TARIF NUMERIC (9) DEFAULT 0 ,
	STATUS_SK VARCHAR (1) DEFAULT '0', 
	KETERANGAN TEXT
)
GO

-- ============================ PEMBUKAAN SARANA PRASARANA (PSP) ===============================-- 
-- KWT_SK_PSP
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_SK_PSP') AND type in (N'U'))
DROP TABLE KWT_SK_PSP
GO
CREATE TABLE KWT_SK_PSP
(
	KODE_SK VARCHAR (3) PRIMARY KEY ,
	NO_SK VARCHAR (50) ,
	TGL_SK DATE , 
	TGL_BERLAKU DATE , 
	PEMBUAT VARCHAR (50) ,
	STATUS_SK VARCHAR (1) DEFAULT '0', 
	KETERANGAN TEXT
)
GO 

-- KWT_TARIF_PSP
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TARIF_PSP') AND type in (N'U'))
DROP TABLE KWT_TARIF_PSP
GO
CREATE TABLE KWT_TARIF_PSP 
(
	KEY_PSP VARCHAR (8) PRIMARY KEY ,
	KODE_SK VARCHAR (3) ,
	KODE_TIPE VARCHAR (1) ,
	KODE_FUNGSI VARCHAR (2) ,
	TARIF NUMERIC (9) DEFAULT 0 ,
	LOKASI TEXT
)
GO

-- KWT_TIPE_PSP
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_TIPE_PSP') AND type in (N'U'))
DROP TABLE KWT_TIPE_PSP
GO
CREATE TABLE KWT_TIPE_PSP 
(
	KODE_TIPE VARCHAR (1) PRIMARY KEY
)
GO 

-- KWT_FUNGSI_PSP
IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'KWT_FUNGSI_PSP') AND type in (N'U'))
DROP TABLE KWT_FUNGSI_PSP
GO
CREATE TABLE KWT_FUNGSI_PSP 
(
	KODE_FUNGSI VARCHAR (2) PRIMARY KEY ,
	NAMA_FUNGSI VARCHAR (50)
)
GO 


