-- ====================== KWT_USER ====================== 
TRUNCATE TABLE KWT_USER 
GO 

INSERT INTO KWT_USER (LOGIN_USER, NAMA_USER, PASS_USER, AKTIF_USER)
VALUES 
('SYSTEM','System',CONVERT(NVARCHAR(32),HashBytes('MD5', 'SYSTEM'), 2),'1'), -- 1 
('VIRTUALACCOUNT','Virtual Account',CONVERT(NVARCHAR(32),HashBytes('MD5', 'VIRTUALACCOUNT'), 2),'1'), -- 2 
('AUTODEBET','Autodebet',CONVERT(NVARCHAR(32),HashBytes('MD5', 'AUTODEBET'), 2),'1'), -- 3 
('DITO','Dito Fityanto',CONVERT(NVARCHAR(32),HashBytes('MD5', 'DITO'), 2),'1'), -- 4

('RAHMAWATI','Rahmawati',CONVERT(NVARCHAR(32),HashBytes('MD5', 'RAHMAWATI'), 2),'1'), -- 5 
('SUSI','Susi',CONVERT(NVARCHAR(32),HashBytes('MD5', 'SUSI'), 2),'1'), -- 6 
('NURLIYA','Nurliya',CONVERT(NVARCHAR(32),HashBytes('MD5', 'NURLIYA'), 2),'1'), --	7 
('YACUB','Yacub',CONVERT(NVARCHAR(32),HashBytes('MD5', 'YACUB'), 2),'1') -- 8 
GO 

-- ====================== KWT_USER_MODUL ====================== 
TRUNCATE TABLE KWT_USER_MODUL 
GO 
INSERT INTO KWT_USER_MODUL (ID_USER, ID_MODUL)
VALUES (4, 'M1'), (4, 'M2'), (4, 'M3'), (4, 'M4'), (4, 'M5'), (4, 'M6'), (4, 'M7'), (4, 'M8'), (4, 'M9'), (4, 'M10'), (4, 'M11'), (4, 'M12'), (4, 'M13'), (4, 'M15'), (4, 'M14'), (4, 'T1'), (4, 'T2'), (4, 'T3'), (4, 'T4'), (4, 'T5'), (4, 'T6'), (4, 'T7'), (4, 'T8'), (4, 'B1'), (4, 'B2'), (4, 'PA1'), (4, 'PA2'), (4, 'PD1'), (4, 'LA1'), (4, 'LA2'), (4, 'LA3'), (4, 'LA4'), (4, 'LA5'), (4, 'LA6'), (4, 'LA7'), (4, 'LA8'), (4, 'LA9'), (4, 'LD1'), (4, 'LD2'), (4, 'LD3'), (4, 'LD4'), (4, 'LD5'), (4, 'LD6'), (4, 'LD7'), (4, 'LP1'), (4, 'LP2'), (4, 'LP3'), (4, 'LB1'), (4, 'LB2'), (4, 'LB3'), (4, 'U1'), (4, 'U2'), (4, 'U3'), (4, 'U4'), (4, 'U5'), (4, 'U6'), (4, 'U7'), (4, 'U8'), (4, 'U9'), (4, 'M1'), (4, 'M2'), (4, 'M3'), (4, 'M4'), (4, 'M5'), (4, 'M6'), (4, 'M7'), (4, 'M8'), (4, 'M9'), (4, 'M10'), (4, 'M11'), (4, 'M12'), (4, 'M13'), (4, 'M14'), (4, 'LP1'), (4, 'LP2'), (4, 'LP3'), (4, 'LB1'), (4, 'LB2'), (4, 'LB3'), (4, 'U1'), (4, 'U2'), (4, 'U3'), (4, 'U4'), (4, 'U5'), (4, 'U6'), (4, 'U7'), (4, 'U8'), (4, 'U9')
GO 



INSERT INTO KWT_USER 
( 
	LOGIN_USER, 
	NAMA_USER, 
	PASS_USER, 
	AKTIF_USER 
) 
SELECT 
	UPPER(dbo.TRIM(KODE_USER)) AS LOGIN_USER, 
	dbo.UCF(LOWER(NAMA_USER)) AS NAMA_USER, 
	CONVERT(NVARCHAR(32),HashBytes('MD5', PASSWORD), 2) AS PASS_USER, 
	1 AS AKTIF_USER 
FROM [pgl].[dbo].[KWT_USER] 
ORDER BY LOGIN_USER
GO 

INSERT INTO KWT_USER 
( 
	LOGIN_USER, 
	NAMA_USER, 
	PASS_USER, 
	AKTIF_USER 
) 
SELECT 
	UPPER(dbo.TRIM(CUSR_NAME)) AS LOGIN_USER, 
	dbo.UCF(LOWER(CUSR_REAL_NAME)) AS NAMA_USER, 
	CONVERT(NVARCHAR(32),HashBytes('MD5', UPPER(dbo.TRIM(CUSR_NAME))), 2) AS PASS_USER, 
	1 AS AKTIF_USER 
FROM [pgl].[dbo].[CLASP_USER]
WHERE UPPER(dbo.TRIM(CUSR_NAME)) NOT IN (SELECT LOGIN_USER FROM [dbpkb].[dbo].[KWT_USER])
ORDER BY LOGIN_USER
GO 

-- ====================== KWT_PARAMETER ====================== 
INSERT INTO KWT_PARAMETER 
( 
	JRP_PT, JRP_KODE_POS, JRP_ALAMAT_1, JRP_TELP, JRP_ALAMAT_2, JRP_FAX, JRP_KOTA, JRP_EMAIL, 
	UNIT_NAMA, UNIT_KODE_POS, UNIT_ALAMAT_1, UNIT_TELP, UNIT_ALAMAT_2, UNIT_FAX, UNIT_KOTA, UNIT_EMAIL, 
	NAMA_PIMPINAN, JBT_PIMPINAN, NAMA_PAJAK, JBT_PAJAK, NAMA_ADM, JBT_ADM, 
	COU_NP, REG_NPWP, PERSEN_PPN, REG_FP, COU_FP, DENDA_RUPIAH, DENDA_PERSEN, 
	
	ADM_KV, REG_IVC_KV, COU_IVC_KV, REG_KWT_KV, COU_KWT_KV, 
	ADM_BG, REG_IVC_BG, COU_IVC_BG, REG_KWT_BG, COU_KWT_BG, 
	ADM_HN, REG_IVC_HN, COU_IVC_HN, REG_KWT_HN, COU_KWT_HN, 
	ADM_RV, REG_IVC_RV, COU_IVC_RV, REG_KWT_RV, COU_KWT_RV, 
	
	ADM_LBG, REG_IVC_LBG, COU_IVC_LBG, REG_KWT_LBG, COU_KWT_LBG, 
	ADM_LRV, REG_IVC_LRV, COU_IVC_LRV, REG_KWT_LRV, COU_KWT_LRV, 
	
	ADM_DBG, REG_IVC_DBG, COU_IVC_DBG, REG_KWT_DBG, COU_KWT_DBG, 
	ADM_DRV, REG_IVC_DRV, COU_IVC_DRV, REG_KWT_DRV, COU_KWT_DRV 
) 
VALUES 
( 
	'PT. JAYA REAL PROPERTY,Tbk', '15227', 'CBD Emerald Blok CE/A No.1', '021-7458888', 'Boulevard Bintaro Jaya Perigi', '021-7456666', 'Tangerang', 'system@jayareal.co.id', 
	'Pengelola Kawasan Bintaro', '1522', 'Bintaro Trade Centre Lt.2 Blok H4 No.1-33', '021-74864001', 'CBD Sektor 7, Bintaro Jaya', '021-74864002', 'Tangerang', 'system@jayareal.co.id', 
	'Wahid Utomo', 'Manager Tata Lingkungan', 'Sayid Agung Wardoyo', 'Kepala Unit Pengelola Kawasan Bintaro', NULL, NULL, 
	17550, '01.001.076.7-411.001', 10, '010.000-14.', 79644110, 10000, 3, 
	
	0, '/TAG-KV/', 1, '/KWI-KV/', 1, 
	0, '/TAG-BG/', 1, '/KWI-BG/', 1, 
	0, '/TAG-HN/', 1, '/KWI/', 1, 
	0, '/TAG-RV/', 1, '/KWI-RV/', 1, 
	
	0, '/TAG-LBG/', 1, '/KWI-LBG/', 1, 
	0, '/TAG-LRV/', 1, '/KWI-LRV/', 1, 
	
	0, '/TAG-DBG/', 1, '/KWI-DBG/', 1, 
	0, '/TAG-DRV/', 1, '/KWI-DRV/', 1 
) 
GO 

-- ====================== KWT_PELANGGAN ====================== 
TRUNCATE TABLE KWT_PELANGGAN 
GO 
INSERT INTO KWT_PELANGGAN 
( 
	NO_PELANGGAN, NAMA_PELANGGAN, NPWP, NO_TELEPON, NO_HP, 
	KODE_BANK, NO_REKENING, KODE_ZONA, TGL_PEMUTUSAN, KEY_AIR, CREATED_DATE, 
	
	INFO_TAGIHAN,
	AKTIF_AD,
	
	KODE_SEKTOR, 
	KODE_CLUSTER, 
	KODE_BLOK, 
	LUAS_KAVLING, 
	LUAS_BANGUNAN, 
	STATUS_BLOK, 
	
	KEY_IPL, 
	TIPE_AIR, 
	TIPE_IPL, 
	NO_KTP, 
	ALAMAT, 
	
	TGL_PPJB, 
	PERIODE_PUTUS, 
	PETUGAS, 
	
	AKTIF_AIR, 
	AKTIF_IPL, 
	
	SM_NO_KTP, 
	SM_NAMA_PELANGGAN, 
	SM_NPWP, 
	SM_ALAMAT, 
	SM_NO_TELEPON, 
	SM_NO_HP, 
	KET,
	
	DISABLED
) 
SELECT 
	NO_PELANGGAN, NAMA_PELANGGAN, NPWP, NO_TELEPON, NO_HP, 
	KODE_BANK, NO_REKENING, KODE_ZONA, TGL_PEMUTUSAN, KEY_AIR, CREATED_DATE, 
	
	ISNULL(INFO_TAGIHAN, 0) AS INFO_TAGIHAN,
	CASE WHEN ISNUMERIC(DEBET_BANK) = 1 THEN 1 ELSE 0 END AS AKTIF_AD,
	
	KODE_SEKTOR, 
	KODE_CLUSTER, 
	KODE_BLOK, 
	ISNULL(LUAS_KAVLING, 0) AS LUAS_KAVLING, 
	ISNULL(LUAS_BANGUNAN, 0) AS LUAS_BANGUNAN, 
	3 AS STATUS_BLOK, 
	
	KEY_KEB AS KEY_IPL, 
	SUBSTRING(KEY_AIR,CHARINDEX('-',KEY_AIR)+1,10) AS TIPE_AIR, 
	SUBSTRING(KEY_KEB,CHARINDEX('-',KEY_KEB)+1,10) AS TIPE_IPL, 
	NO_PELANGGAN AS NO_KTP, 
	ALAMAT_1 + ' ' + ALAMAT_2 AS ALAMAT, 
	
	TGL_SERAHTERIMA AS TGL_PPJB, 
	(RIGHT(PERIODE_PUTUS,4) + LEFT(PERIODE_PUTUS,2)) AS PERIODE_PUTUS, 
	PETUGAS, 
	
	0 AS AKTIF_AIR, 
	0 AS AKTIF_IPL, 
	
	NO_PELANGGAN AS SM_NO_KTP , 
	NAMA_PELANGGAN AS SM_NAMA_PELANGGAN , 
	NPWP AS SM_NPWP , 
	ALAMAT_1 + ' ' + ALAMAT_2 AS SM_ALAMAT , 
	NO_TELEPON AS SM_NO_TELEPON , 
	NO_HP AS SM_NO_HP, 
	
	KETERANGAN AS KET, 
	
	CASE WHEN STATUS = 'S' THEN 1 ELSE 0 END AS DISABLED 
	
FROM [pgl].[dbo].[KWT_PELANGGAN] 
GO 

INSERT INTO KWT_PEMUTUSAN_AIR (NO_PELANGGAN, PERIODE_PUTUS, TGL_PEMUTUSAN, PETUGAS) 
SELECT 
	NO_PELANGGAN, 
	PERIODE_PUTUS, 
	TGL_PEMUTUSAN, 
	PETUGAS 
FROM 
	KWT_PELANGGAN WHERE TGL_PEMUTUSAN IS NOT NULL 
GO 

-- ====================== KWT_PELANGGAN_LOOKUP ====================== 
TRUNCATE TABLE KWT_PELANGGAN_LOOKUP 
GO 
INSERT INTO KWT_PELANGGAN_LOOKUP 
( 
	NO_KTP, NAMA_PELANGGAN, NPWP, ALAMAT, NO_TELEPON, NO_HP, 
	SM_NO_KTP, SM_NAMA_PELANGGAN, SM_NPWP, SM_ALAMAT, SM_NO_TELEPON, SM_NO_HP, 
	KODE_BANK, NO_REKENING 
) 
SELECT 
	NO_KTP, NAMA_PELANGGAN, NPWP, ALAMAT, NO_TELEPON, NO_HP, 
	SM_NO_KTP, SM_NAMA_PELANGGAN, SM_NPWP, SM_ALAMAT, SM_NO_TELEPON, SM_NO_HP, 
	KODE_BANK, NO_REKENING 
FROM KWT_PELANGGAN 
GO 

-- ====================== AIR ====================== 
-- ======= KWT_SK_AIR 
TRUNCATE TABLE KWT_SK_AIR 
GO 
INSERT INTO KWT_SK_AIR 
( 
	KODE_SK, 
	NO_SK, 
	TGL_SK, 
	TGL_BERLAKU, 
	PEMBUAT, 
	STATUS_SK, 
	KET 
) 
SELECT 
	KODE_SK_AIR AS KODE_SK, 
	NO_SK_AIR AS NO_SK, 
	TGL_SK, 
	TGL_BERLAKU, 
	PEMBUAT, 
	0 AS STATUS_SK, 
	KETERANGAN AS KET 
FROM [pgl].[dbo].[KWT_HDR_AIR] 
GO 

UPDATE KWT_SK_AIR SET STATUS_SK = 1 
WHERE 
	KODE_SK = (SELECT TOP 1 KODE_SK FROM KWT_SK_AIR ORDER BY TGL_BERLAKU DESC) 
GO 

-- ======= KWT_TIPE_AIR 
TRUNCATE TABLE KWT_TIPE_AIR 
GO 
INSERT INTO KWT_TIPE_AIR 
( 
	KODE_TIPE, 
	NAMA_TIPE, 
	PERSEN_ASUMSI_1, 
	PERSEN_ASUMSI_2, 
	PERSEN_ASUMSI_3, 
	PERSEN_ASUMSI_4
) 
SELECT 
	KODE_TIPE, 
	NAMA_TIPE, 
	ISNULL(PROSEN_ASUMSI_1, 0) AS PERSEN_ASUMSI_1, 
	ISNULL(PROSEN_ASUMSI_2, 0) AS PERSEN_ASUMSI_2, 
	ISNULL(PROSEN_ASUMSI_3, 0) AS PERSEN_ASUMSI_3, 
	ISNULL(PROSEN_ASUMSI_4, 0) AS PERSEN_ASUMSI_4
FROM [pgl].[dbo].[KWT_TIPE] 
GO 

-- ======= KWT_TARIF_AIR 
TRUNCATE TABLE KWT_TARIF_AIR 
GO 
INSERT INTO KWT_TARIF_AIR 
( 
	KEY_AIR, 
	KODE_SK, 
	KODE_TIPE, 
	ABONEMEN, 
	STAND_MIN_PAKAI, 
	BLOK1, 
	BLOK2, 
	BLOK3, 
	BLOK4, 
	TARIF1, 
	TARIF2, 
	TARIF3, 
	TARIF4, 
	KET 
) 
SELECT 
	KEY_AIR, 
	KODE_SK_AIR AS KODE_SK, 
	KODE_TIPE, 
	ABONEMEN, 
	(CASE WHEN KODE_TIPE LIKE '%X0%' THEN 0 ELSE 5 END) AS STAND_MIN_PAKAI, 
	BLOK1, 
	BLOK2, 
	BLOK3, 
	BLOK4, 
	TARIP1 AS TARIF1, 
	TARIP2 AS TARIF2, 
	TARIP3 AS TARIF3, 
	TARIP4 AS TARIF4, 
	KETERANGAN AS KET 
FROM [pgl].[dbo].[KWT_DTL_AIR] 
GO 


-- ====================== IPL ====================== 
-- ======= KWT_SK_IPL 
TRUNCATE TABLE KWT_SK_IPL 
GO 
INSERT INTO KWT_SK_IPL 
( 
	KODE_SK, 
	NO_SK, 
	TGL_SK, 
	TGL_BERLAKU, 
	PEMBUAT, 
	STATUS_SK, 
	KET 
) 
SELECT 
	KODE_SK_KEB AS KODE_SK, 
	NO_SK_KEB AS NO_SK, 
	TGL_SK, 
	TGL_BERLAKU, 
	PEMBUAT, 
	0 AS STATUS_SK, 
	KETERANGAN AS KET 
FROM [pgl].[dbo].[KWT_HDR_KEB] 
GO 

UPDATE KWT_SK_IPL SET STATUS_SK = 1 
WHERE 
	KODE_SK = (SELECT TOP 1 KODE_SK FROM KWT_SK_IPL ORDER BY TGL_BERLAKU DESC) 
GO 

-- ======= KWT_TIPE_IPL 
TRUNCATE TABLE KWT_TIPE_IPL 
GO 
INSERT INTO KWT_TIPE_IPL 
( 
	KODE_TIPE, 
	NAMA_TIPE, 
	STATUS_BLOK 
) 
SELECT 
	REPLACE(KODE_TIPE, ' ', '-'), 
	NAMA_TIPE, 
	3 AS STATUS_BLOK 
FROM [pgl].[dbo].[KWT_TIPE_KEB] 
GO 

-- ======= KWT_TARIF_IPL 
TRUNCATE TABLE KWT_TARIF_IPL 
GO 
INSERT INTO KWT_TARIF_IPL 
( 
	KEY_IPL, 
	KODE_SK, 
	KODE_TIPE, 
	TIPE_TARIF_IPL, 
	TARIF_IPL, -- UNTUK PROSES DENDA (0 = STANDAR) (1 = BISNIS) 
	NILAI_DEPOSIT, 
	KET 
) 
SELECT 
	REPLACE(KEY_KEB, ' ', '-') AS KEY_IPL, 
	KODE_SK_KEB AS KODE_SK, 
	REPLACE(KODE_TIPE, ' ', '-'), 
	0 AS TIPE_TARIF_IPL, 
	TARIF_KEB AS TARIF_IPL, 
	0 AS NILAI_DEPOSIT, 
	KETERANGAN AS KET 
FROM [pgl].[dbo].[KWT_DTL_KEB] 
GO 

UPDATE KWT_TARIF_IPL SET TIPE_TARIF_IPL = 1 
WHERE 
	KODE_TIPE LIKE '%BB%' OR KODE_TIPE LIKE '%BS%' 
GO 

-- ====================== KWT_POST_PEMBAYARAN ====================== 
TRUNCATE TABLE KWT_POST_PEMBAYARAN 
GO 
INSERT INTO KWT_POST_PEMBAYARAN 
( 
	USER_POST, 
	TGL_POST 
) 
SELECT 
	USER_POS AS USER_POST, 
	TGL_POS AS TGL_POST
FROM [pgl].[dbo].[KWT_HDR_POS_REALISASI] 
GO 

-- ====================== KWT_POST_FP ====================== 
TRUNCATE TABLE KWT_POST_FP 
GO 
INSERT INTO KWT_POST_FP 
( 
	USER_POST, 
	TGL_POST 
) 
SELECT 
	'DITO' AS USER_POST, 
	TANGGAL AS TGL_POST 
FROM [pgl].[dbo].[KWT_POSTING_FAKTUR_PAJAK] 
GO 

-- ====================== KWT_BANK ====================== 
TRUNCATE TABLE KWT_BANK 
GO 
INSERT INTO KWT_BANK 
( 
	KODE_BANK, 
	NAMA_BANK, 
	CABANG_BANK, 
	ALAMAT_BANK,
	COU_BD,
	COU_BDT 
) 
SELECT 
	KODE_BANK, 
	NAMA_BANK, 
	CB_BANK AS CABANG_BANK, 
	(ALAMAT_1 + ' ' + ALAMAT_2) AS ALAMAT_BANK,
	1,
	1
FROM [pgl].[dbo].[KWT_BANK] 
GO 

-- ====================== KWT_SEKTOR ====================== 
TRUNCATE TABLE KWT_SEKTOR 
GO 
INSERT INTO KWT_SEKTOR 
( 
	KODE_SEKTOR, 
	NAMA_SEKTOR, 
	KODE_PEL 
) 
SELECT 
	KODE_SEKTOR, 
	NAMA_SEKTOR, 
	KODE_PEL 
FROM [pgl].[dbo].[KWT_SEKTOR] 
GO 

-- ====================== KWT_CLUSTER ====================== 
TRUNCATE TABLE KWT_CLUSTER 
GO 
INSERT INTO KWT_CLUSTER 
( 
	KODE_CLUSTER, 
	KODE_SEKTOR, 
	NAMA_CLUSTER 
) 
SELECT 
	KODE_CLUSTER, 
	KODE_SEKTOR, 
	NAMA_CLUSTER 
FROM [pgl].[dbo].[KWT_CLUSTER] 
GO 

-- ====================== KWT_DISKON_KHUSUS ====================== 
TRUNCATE TABLE KWT_DISKON_KHUSUS 
GO 
INSERT INTO KWT_DISKON_KHUSUS 
( 
	KODE_BLOK, 
	PERIODE_IPL_AWAL, 
	PERIODE_IPL_AKHIR, 
	DISKON_AIR_NILAI, 
	DISKON_IPL_NILAI, 
	DISKON_AIR_PERSEN, 
	DISKON_IPL_PERSEN, 
	KET 
) 
SELECT 
	KODE_BLOK, 
	RIGHT(PERIODE_AWAL,4) + LEFT(PERIODE_AWAL,2) AS PERIODE_IPL_AWAL, 
	RIGHT(PERIODE_AKHIR,4) + LEFT(PERIODE_AKHIR,2) AS PERIODE_IPL_AKHIR, 
	ISNULL(DISKON_AIR_NILAI, 0) AS DISKON_AIR_NILAI, 
	ISNULL(DISKON_IPL_NILAI, 0) AS DISKON_IPL_NILAI, 
	ISNULL(DISKON_AIR_PERSEN, 0) AS DISKON_AIR_PERSEN, 
	ISNULL(DISKON_IPL_PERSEN, 0) AS DISKON_IPL_PERSEN, 
	KETERANGAN AS KET 
FROM [pgl].[dbo].[KWT_DISKON_KHUSUS] 
GO 

-- ====================== KWT_ZMB ====================== 
TRUNCATE TABLE KWT_ZMB 
GO 
INSERT INTO KWT_ZMB(KODE_ZONA,NAMA_ZONA) 
SELECT KODE_ZONA, NAMA_ZONA FROM [pgl].[dbo].[KWT_ZONA_METER_BALANCE] 
GO 

-- ====================== KWT_PEMBAYARAN_AI ====================== 
TRUNCATE TABLE KWT_PEMBAYARAN_AI 
GO 
INSERT INTO KWT_PEMBAYARAN_AI 
( 
	ID_PEMBAYARAN, 
	TRX, 
	
	NO_INVOICE, 
	TGL_JATUH_TEMPO, 
	KET_IVC, 
	
	PERIODE_TAG, 
	PERIODE_AIR, 
	PERIODE_IPL_AWAL, 
	PERIODE_IPL_AKHIR, 
	JUMLAH_PERIODE_IPL, 
	
	NO_PELANGGAN, 
	
	KODE_SEKTOR, 
	KODE_CLUSTER, 
	KODE_BLOK, 
	STATUS_BLOK, 
	
	KODE_ZONA, 
	
	AKTIF_AIR, 
	AKTIF_IPL, 
	
	KEY_AIR, 
	KEY_IPL, 
	
	STAND_LALU, 
	STAND_ANGKAT, 
	STAND_AKHIR, 
	
	BLOK1, 
	BLOK2, 
	BLOK3, 
	BLOK4, 
	STAND_MIN_PAKAI, 
	TARIF1, 
	TARIF2, 
	TARIF3, 
	TARIF4, 
	TARIF_MIN_PAKAI, 
	
	LUAS_KAVLING, 
	TARIF_IPL, 
	
	JUMLAH_AIR, 
	ABONEMEN, 
	JUMLAH_IPL, 
	DENDA, 
	ADM, 
	JUMLAH_BAYAR, 
	
	DISKON_AIR, 
	TGL_DISKON_AIR, 
	USER_DISKON_AIR, 
	KET_DISKON_AIR, 
	
	DISKON_IPL, 
	TGL_DISKON_IPL, 
	USER_DISKON_IPL, 
	KET_DISKON_IPL, 
	
	PERSEN_PPN, 
	NILAI_PPN, 
	
	STATUS_BAYAR, 
	NO_KWITANSI, 
	BAYAR_VIA, 
	CARA_BAYAR, 
	
	TGL_BAYAR_BANK, 
	TGL_BAYAR_SYS, 
	USER_BAYAR, 
	KET_BAYAR, 
	
	STATUS_CETAK_KWT, 
	USER_CETAK_KWT, 
	TGL_CETAK_KWT, 
	
	STATUS_CETAK_IVC, 
	TGL_CETAK_IVC,
	
	STATUS_BATAL, 
	USER_BATAL, 
	TGL_BATAL, 
	KET_BATAL, 
	
	STATUS_POST_PB, 
	STATUS_POST_BD, 
	
	NO_FP, 
	TGL_FP, 
	TGL_POST_FP, 
	
	USER_MODIFIED, 
	MODIFIED_DATE, 
	USER_CREATED, 
	CREATED_DATE
) 
SELECT 
	'3#' + RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) + '#' + b.NO_PELANGGAN AS ID_PEMBAYARAN, 
	3 AS TRX, 
	
	NULL AS NO_INVOICE, 
	NULL AS TGL_JATUH_TEMPO, 
	NULL AS KET_IVC, 
	
	RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) AS PERIODE_TAG, 
	RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) AS PERIODE_AIR, 
	RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) AS PERIODE_IPL_AWAL, 
	RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) AS PERIODE_IPL_AKHIR, 
	1 AS JUMLAH_PERIODE_IPL,
	
	b.NO_PELANGGAN AS NO_PELANGGAN, 
	
	b.KODE_SEKTOR AS KODE_SEKTOR, 
	b.KODE_CLUSTER AS KODE_CLUSTER, 
	b.KODE_BLOK AS KODE_BLOK, 
	3 AS STATUS_BLOK, 
	
	b.KODE_ZONA AS KODE_ZONA, 
	
	1 AS AKTIF_AIR, 
	1 AS AKTIF_IPL,
	
	b.KEY_AIR AS KEY_AIR, 
	b.KEY_KEB AS KEY_IPL, 
	
	ISNULL(b.STAND_LALU, 0) AS STAND_LALU, 
	ISNULL(b.STAND_ANGKAT, 0) AS STAND_ANGKAT, 
	ISNULL(b.STAND_AKHIR, 0) AS STAND_AKHIR, 
	
	ISNULL(b.BLOK1, 0) AS BLOK1, 
	ISNULL(b.BLOK2, 0) AS BLOK2, 
	ISNULL(b.BLOK3, 0) AS BLOK3, 
	ISNULL(b.BLOK4, 0) AS BLOK4,
	
	ISNULL(b.STAND_MIN_PAKAI, 0) AS STAND_MIN_PAKAI, 
	ISNULL(b.TARIP1, 0) AS TARIF1, 
	ISNULL(b.TARIP2, 0) AS TARIF2, 
	ISNULL(b.TARIP3, 0) AS TARIF3, 
	ISNULL(b.TARIP4, 0) AS TARIF4, 
	ISNULL(b.TARIP_MIN_PAKAI, 0) AS TARIF_MIN_PAKAI, 
	
	ISNULL(p.LUAS_KAVLING, 0) AS LUAS_KAVLING, 
	ISNULL(i.TARIF_IPL, 0) AS TARIF_IPL, 
	
	ISNULL(b.JUMLAH_AIR, 0) AS JUMLAH_AIR, 
	ISNULL(b.ABONEMEN, 0) AS ABONEMEN, 
	ISNULL(b.NILAI_SAMPAH, 0) AS JUMLAH_IPL, 
	ISNULL(b.DENDA, 0) AS DENDA, 
	ISNULL(b.ADMINISTRASI, 0) AS ADM, 
	ISNULL(b.JUMLAH_BAYAR, 0) AS JUMLAH_BAYAR, 
	
	ISNULL(b.DISC_RUPIAH, 0) AS DISKON_AIR, 
	b.TGL_DISC AS TGL_DISKON_AIR, 
	b.USER_DISC AS USER_DISKON_AIR, 
	b.KET_DISCOUNT AS KET_DISKON_AIR, 
	
	ISNULL(b.DISC_RUPIAH_IPL, 0) AS DISKON_IPL, 
	b.TGL_DISC_IPL AS TGL_DISKON_IPL, 
	b.USER_DISC_IPL AS USER_DISKON_IPL, 
	b.KET_DISCOUNT AS KET_DISKON_IPL, 
	
	ISNULL(b.PROSEN_PPN, 10) AS PERSEN_PPN, 
	ISNULL(b.NILAI_PPN, 0) AS NILAI_PPN,
	
	(CASE WHEN b.STATUS_BAYAR = '2' THEN 1 ELSE 0 END) AS STATUS_BAYAR,
	b.NO_KWITANSI AS NO_KWITANSI, 
	b.BAYAR_MELALUI AS BAYAR_VIA, 
	(CASE WHEN ISNUMERIC(b.JENIS_BAYAR) = 1 THEN b.JENIS_BAYAR ELSE 0 END) AS CARA_BAYAR,
	
	b.TGL_BAYAR AS TGL_BAYAR_BANK, 
	b.TGL_TERIMA_BANK AS TGL_BAYAR_SYS,
	b.KASIR AS USER_BAYAR, 
	b.KETERANGAN AS KET_BAYAR, 
	
	ISNULL(b.JUMLAH_CETAK, 0) AS STATUS_CETAK_KWT, 
	(CASE WHEN b.JUMLAH_CETAK = '1' THEN b.KASIR END) AS USER_CETAK_KWT, 
	(CASE WHEN b.JUMLAH_CETAK = '1' THEN b.TGL_TERIMA_BANK END) AS TGL_CETAK_KWT, 
	
	0 AS STATUS_CETAK_IVC, 
	NULL AS TGL_CETAK_IVC, 
	
	ISNULL(b.STATUS_BATAL, 0) AS STATUS_BATAL,
	b.USER_BATAL AS USER_BATAL, 
	b.TGL_BATAL AS TGL_BATAL, 
	NULL AS KET_BATAL, 
	
	ISNULL(b.STATUS_POS, 0) AS STATUS_POST_PB, 
	0 AS STATUS_POST_BD, 
	
	b.NO_FAKTUR_PAJAK AS NO_FP, 
	b.TGL_FAKTUR_PAJAK AS TGL_FP, 
	b.TGL_POSTING_FAKTUR_PAJAK AS TGL_POST_FP, 
	
	b.USER_EDIT AS USER_MODIFIED, 
	b.TGL_EDIT AS MODIFIED_DATE,
	'1' AS USER_CREATED, 
	GETDATE() AS CREATED_DATE
	
FROM 
	[pgl].[dbo].[KWT_PEMBAYARAN] b 
	LEFT JOIN KWT_PELANGGAN p ON b.NO_PELANGGAN = p.NO_PELANGGAN 
	LEFT JOIN KWT_TARIF_IPL i ON b.KEY_KEB = i.KEY_IPL 
	LEFT JOIN KWT_TIPE_IPL t ON i.KODE_TIPE = t.KODE_TIPE 
GO 

-- ================================== NON AKTIF ==================================
INSERT INTO KWT_PEMBAYARAN_AI 
( 
	ID_PEMBAYARAN, 
	TRX, 
	
	NO_INVOICE, 
	TGL_JATUH_TEMPO, 
	KET_IVC, 
	
	PERIODE_TAG, 
	PERIODE_AIR, 
	PERIODE_IPL_AWAL, 
	PERIODE_IPL_AKHIR, 
	JUMLAH_PERIODE_IPL, 
	
	NO_PELANGGAN, 
	
	KODE_SEKTOR, 
	KODE_CLUSTER, 
	KODE_BLOK, 
	STATUS_BLOK, 
	
	KODE_ZONA, 
	
	AKTIF_AIR, 
	AKTIF_IPL, 
	
	KEY_AIR, 
	KEY_IPL, 
	
	STAND_LALU, 
	STAND_ANGKAT, 
	STAND_AKHIR, 
	
	BLOK1, 
	BLOK2, 
	BLOK3, 
	BLOK4, 
	STAND_MIN_PAKAI, 
	TARIF1, 
	TARIF2, 
	TARIF3, 
	TARIF4, 
	TARIF_MIN_PAKAI, 
	
	LUAS_KAVLING, 
	TARIF_IPL, 
	
	JUMLAH_AIR, 
	ABONEMEN, 
	JUMLAH_IPL, 
	DENDA, 
	ADM, 
	JUMLAH_BAYAR, 
	
	DISKON_AIR, 
	TGL_DISKON_AIR, 
	USER_DISKON_AIR, 
	KET_DISKON_AIR, 
	
	DISKON_IPL, 
	TGL_DISKON_IPL, 
	USER_DISKON_IPL, 
	KET_DISKON_IPL, 
	
	PERSEN_PPN, 
	NILAI_PPN, 
	
	STATUS_BAYAR, 
	NO_KWITANSI, 
	BAYAR_VIA, 
	CARA_BAYAR, 
	
	TGL_BAYAR_BANK, 
	TGL_BAYAR_SYS, 
	USER_BAYAR, 
	KET_BAYAR, 
	
	STATUS_CETAK_KWT, 
	USER_CETAK_KWT, 
	TGL_CETAK_KWT, 
	
	STATUS_CETAK_IVC, 
	TGL_CETAK_IVC,
	
	STATUS_BATAL, 
	USER_BATAL, 
	TGL_BATAL, 
	KET_BATAL, 
	
	STATUS_POST_PB, 
	STATUS_POST_BD, 
	
	NO_FP, 
	TGL_FP, 
	TGL_POST_FP, 
	
	USER_MODIFIED, 
	MODIFIED_DATE, 
	USER_CREATED, 
	CREATED_DATE
) 
SELECT 
	'3#' + RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) + '#' + b.NO_PELANGGAN AS ID_PEMBAYARAN, 
	3 AS TRX, 
	
	NULL AS NO_INVOICE, 
	NULL AS TGL_JATUH_TEMPO, 
	NULL AS KET_IVC, 
	
	RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) AS PERIODE_TAG, 
	RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) AS PERIODE_AIR, 
	RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) AS PERIODE_IPL_AWAL, 
	RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) AS PERIODE_IPL_AKHIR, 
	1 AS JUMLAH_PERIODE_IPL, 
	
	b.NO_PELANGGAN AS NO_PELANGGAN, 
	
	b.KODE_SEKTOR AS KODE_SEKTOR, 
	b.KODE_CLUSTER AS KODE_CLUSTER, 
	b.KODE_BLOK AS KODE_BLOK, 
	3 AS STATUS_BLOK, 
	
	b.KODE_ZONA AS KODE_ZONA, 
	
	1 AS AKTIF_AIR, 
	1 AS AKTIF_IPL,
	
	b.KEY_AIR AS KEY_AIR, 
	b.KEY_KEB AS KEY_IPL, 
	
	ISNULL(b.STAND_LALU, 0) AS STAND_LALU, 
	ISNULL(b.STAND_ANGKAT, 0) AS STAND_ANGKAT, 
	ISNULL(b.STAND_AKHIR, 0) AS STAND_AKHIR, 
	
	ISNULL(b.BLOK1, 0) AS BLOK1, 
	ISNULL(b.BLOK2, 0) AS BLOK2, 
	ISNULL(b.BLOK3, 0) AS BLOK3, 
	ISNULL(b.BLOK4, 0) AS BLOK4,
	
	ISNULL(b.STAND_MIN_PAKAI, 0) AS STAND_MIN_PAKAI, 
	ISNULL(b.TARIP1, 0) AS TARIF1, 
	ISNULL(b.TARIP2, 0) AS TARIF2, 
	ISNULL(b.TARIP3, 0) AS TARIF3, 
	ISNULL(b.TARIP4, 0) AS TARIF4, 
	ISNULL(b.TARIP_MIN_PAKAI, 0) AS TARIF_MIN_PAKAI, 
	
	ISNULL(p.LUAS_KAVLING, 0) AS LUAS_KAVLING, 
	ISNULL(i.TARIF_IPL, 0) AS TARIF_IPL, 
	
	ISNULL(b.JUMLAH_AIR, 0) AS JUMLAH_AIR, 
	ISNULL(b.ABONEMEN, 0) AS ABONEMEN, 
	ISNULL(b.NILAI_SAMPAH, 0) AS JUMLAH_IPL, 
	ISNULL(b.DENDA, 0) AS DENDA, 
	ISNULL(b.ADMINISTRASI, 0) AS ADM, 
	ISNULL(b.JUMLAH_BAYAR, 0) AS JUMLAH_BAYAR, 
	
	ISNULL(b.DISC_RUPIAH, 0) AS DISKON_AIR, 
	b.TGL_DISC AS TGL_DISKON_AIR, 
	b.USER_DISC AS USER_DISKON_AIR, 
	b.KET_DISCOUNT AS KET_DISKON_AIR, 
	
	ISNULL(b.DISC_RUPIAH_IPL, 0) AS DISKON_IPL, 
	b.TGL_DISC_IPL AS TGL_DISKON_IPL, 
	b.USER_DISC_IPL AS USER_DISKON_IPL, 
	b.KET_DISCOUNT AS KET_DISKON_IPL, 
	
	ISNULL(b.PROSEN_PPN, 10) AS PERSEN_PPN, 
	ISNULL(b.NILAI_PPN, 0) AS NILAI_PPN,
	
	(CASE WHEN b.STATUS_BAYAR = '2' THEN 1 ELSE 0 END) AS STATUS_BAYAR,
	b.NO_KWITANSI AS NO_KWITANSI, 
	b.BAYAR_MELALUI AS BAYAR_VIA, 
	(CASE WHEN ISNUMERIC(b.JENIS_BAYAR) = 1 THEN b.JENIS_BAYAR ELSE 0 END) AS CARA_BAYAR,
	
	b.TGL_BAYAR AS TGL_BAYAR_BANK, 
	b.TGL_TERIMA_BANK AS TGL_BAYAR_SYS,
	b.KASIR AS USER_BAYAR, 
	b.KETERANGAN AS KET_BAYAR, 
	
	ISNULL(b.JUMLAH_CETAK, 0) AS STATUS_CETAK_KWT, 
	(CASE WHEN b.JUMLAH_CETAK = '1' THEN b.KASIR END) AS USER_CETAK_KWT, 
	(CASE WHEN b.JUMLAH_CETAK = '1' THEN b.TGL_TERIMA_BANK END) AS TGL_CETAK_KWT, 
	
	0 AS STATUS_CETAK_IVC, 
	NULL AS TGL_CETAK_IVC, 
	
	ISNULL(b.STATUS_BATAL, 0) AS STATUS_BATAL,
	b.USER_BATAL AS USER_BATAL, 
	b.TGL_BATAL AS TGL_BATAL, 
	NULL AS KET_BATAL, 
	
	ISNULL(b.STATUS_POS, 0) AS STATUS_POST_PB, 
	0 AS STATUS_POST_BD, 
	
	b.NO_FAKTUR_PAJAK AS NO_FP, 
	b.TGL_FAKTUR_PAJAK AS TGL_FP, 
	b.TGL_POSTING_FAKTUR_PAJAK AS TGL_POST_FP, 
	
	b.USER_EDIT AS USER_MODIFIED, 
	b.TGL_EDIT AS MODIFIED_DATE,
	'1' AS USER_CREATED, 
	GETDATE() AS CREATED_DATE
	
FROM 
	[pgl].[dbo].[KWT_PEMBAYARAN_PEL_NON_AKTIF] b 
	LEFT JOIN KWT_PELANGGAN p ON b.NO_PELANGGAN = p.NO_PELANGGAN 
	LEFT JOIN KWT_TARIF_IPL i ON b.KEY_KEB = i.KEY_IPL 
	LEFT JOIN KWT_TIPE_IPL t ON i.KODE_TIPE = t.KODE_TIPE 
GO 



--===================== UPDATE KWT_PEMBAYARAN HUNIAN 
UPDATE KWT_PEMBAYARAN_AI SET USER_BAYAR = NULL WHERE USER_BAYAR = '-'
UPDATE KWT_PEMBAYARAN_AI SET USER_CETAK_KWT = NULL WHERE USER_CETAK_KWT = '-'
UPDATE KWT_PEMBAYARAN_AI SET USER_DISKON_AIR = NULL WHERE USER_DISKON_AIR = '-'
UPDATE KWT_PEMBAYARAN_AI SET USER_DISKON_IPL = NULL WHERE USER_DISKON_IPL = '-'
UPDATE KWT_PEMBAYARAN_AI SET USER_BATAL = NULL WHERE USER_BATAL = '-'
UPDATE KWT_PEMBAYARAN_AI SET USER_MODIFIED = NULL WHERE USER_MODIFIED = '-'
UPDATE KWT_PEMBAYARAN_AI SET USER_CREATED = NULL WHERE USER_CREATED = '-'

UPDATE KWT_PEMBAYARAN_AI SET AKTIF_AIR = 0 WHERE ABONEMEN <= 0 
UPDATE KWT_PEMBAYARAN_AI SET AKTIF_IPL = 0 WHERE JUMLAH_IPL <= 0 
UPDATE KWT_PEMBAYARAN_AI SET PERSEN_PPN = 10 WHERE PERSEN_PPN = 0 
UPDATE KWT_PEMBAYARAN_AI SET CARA_BAYAR = 4 WHERE STATUS_BAYAR = 1 AND CARA_BAYAR = 0 
GO 

UPDATE KWT_PEMBAYARAN_AI SET USER_BAYAR = 'VIRTUAL ACCOUNT'
WHERE 
	STATUS_BAYAR = 1 
	AND USER_MODIFIED = 'VIRTUAL ACCOUNT'
GO 

UPDATE KWT_PEMBAYARAN_AI SET USER_BAYAR = 'AUTODEBET'
WHERE 
	STATUS_BAYAR = 1 
	AND USER_MODIFIED IS NULL 
	AND USER_BAYAR IS NULL
GO 

UPDATE KWT_PEMBAYARAN_AI 
SET KEY_AIR = dbo.ETN(dbo.TRIM(KEY_AIR)), 
	KEY_IPL = dbo.ETN(dbo.TRIM(KEY_IPL)),
	PERIODE_TAG = CONVERT(VARCHAR(6), DATEADD(MONTH, 1, CAST(PERIODE_TAG + '01' AS DATE)), 112), 
	JUMLAH_AIR = (
		(BLOK1 * TARIF1) + (BLOK2 * TARIF2) + 
		(BLOK3 * TARIF3) + (BLOK4 * TARIF4) + 
		(STAND_MIN_PAKAI * TARIF_MIN_PAKAI)
	)	
GO 
UPDATE KWT_PEMBAYARAN_AI 
SET	ID_PEMBAYARAN = '3#' + PERIODE_TAG + '#' + NO_PELANGGAN, 
	TGL_JATUH_TEMPO = CAST(PERIODE_TAG + '25' AS DATE),
	CREATED_DATE = CAST(PERIODE_TAG + '06' AS DATE) 
GO 

UPDATE KWT_PEMBAYARAN_AI 
SET JUMLAH_BAYAR = (
	JUMLAH_AIR + ABONEMEN + 
	JUMLAH_IPL + ADM + DENDA - 
	DISKON_AIR - DISKON_IPL
)
WHERE 
	STATUS_BAYAR = 1 
GO 

UPDATE KWT_PEMBAYARAN_AI 
SET PERIODE_IPL_AWAL = NULL, 
	PERIODE_IPL_AKHIR = NULL, 
	JUMLAH_PERIODE_IPL = 0 
WHERE AKTIF_IPL = 0 
GO 





