-- ====================== IPL ====================== 
-- UPDATE KODE_SK
UPDATE [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] SET IUAFD_SK = '014' WHERE IUAFD_SK = 'SK2014'
UPDATE [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] SET IUAFD_SK = '013' WHERE IUAFD_SK = 'SK2013'
UPDATE [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] SET IUAFD_SK = '012' WHERE 
	IUAFD_SK = '649/JRP/DIR/PKB/XI/2011'
	OR IUAFD_SK = '651/JRP/DIR/PKB/XI/2011'
	OR IUAFD_SK = '652/JRP/DIR/PKB/XI/2011'
UPDATE [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] SET IUAFD_SK = '011' WHERE 
	IUAFD_SK = '051/JRP/DIR/PKB/XI/2010'
	OR IUAFD_SK = '052/JRP/DIR/PKB/XI/2010'
UPDATE [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] SET IUAFD_SK = '010' WHERE 
	IUAFD_SK = 'SK 2010'
	OR IUAFD_SK = '049/JRP/DIR/PKB/XI/2010'
UPDATE [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] SET IUAFD_SK = '009' WHERE 
	IUAFD_SK = 'SK 2009'
	OR IUAFD_SK = '039/JRP/DIR/PKB/XII/2009'
	OR IUAFD_SK = '040/JRP/DIR/PKB/XII/2009'
	OR IUAFD_SK = '042/JRP/DIR/PKB/XII/2009'
UPDATE [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] SET IUAFD_SK = '007' WHERE IUAFD_SK = 'SK Juni 2007 - Desember 2008'
UPDATE [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] SET IUAFD_SK = '006' WHERE IUAFD_SK = 'SK APRIL 2006 - MEI 2007'
UPDATE [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] SET IUAFD_SK = '000' WHERE IUAFD_SK = 'SK 2000 - MARET 2006'
UPDATE [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] SET IUAFD_SK = '095' WHERE IUAFD_SK = 'SK 1995 - 1999'
UPDATE [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] SET IUAFD_SK = '094' WHERE IUAFD_SK = 'SK < 1995'
GO

-- SK IPL
INSERT INTO KWT_SK_IPL 
( 
	KODE_SK, 
	NO_SK, 
	TGL_SK, 
	TGL_BERLAKU, 
	PEMBUAT, 
	STATUS_SK, 
	KET 
) 
SELECT 
	DISTINCT d.IUAFD_SK AS KODE_SK, 
	d.IUAFD_SK AS NO_SK, 
	NULL AS TGL_SK, 
	NULL AS TGL_BERLAKU, 
	NULL AS PEMBUAT, 
	0 STATUS_SK, 
	NULL AS KET 
FROM 
	[pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] d 
WHERE 
	d.IUAFD_SK NOT IN (SELECT KODE_SK FROM KWT_SK_IPL) 
GO 

-- TIPE IPL
-- ======= CEK_DOUBLE_KEY_IPL 
SELECT (IUAFD_SK + '#' + CAST(IUAFD_AREA_CLASS_ID AS VARCHAR)) AS CEK_DOUBLE_KEY_IPL
FROM [pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL]
GROUP BY (IUAFD_SK + '#' + CAST(IUAFD_AREA_CLASS_ID AS VARCHAR))
HAVING COUNT((IUAFD_SK + '#' + CAST(IUAFD_AREA_CLASS_ID AS VARCHAR))) > 1


-- ======= KWT_TIPE_IPL 
DELETE FROM KWT_TIPE_IPL WHERE STATUS_BLOK = 1 
GO 
INSERT INTO KWT_TIPE_IPL 
( 
	KODE_TIPE, 
	NAMA_TIPE, 
	STATUS_BLOK 
) 
SELECT 
	REPLACE(c.IUAC_CODE, ' ', '-') AS KODE_TIPE, 
	c.IUAC_NAME AS NAMA_TIPE, 
	1 AS STATUS_BLOK
FROM 
	[pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] d
	JOIN [pgl].[dbo].[IPL_UNIT_AREA_FEE] f ON d.IUAFD_FEE_ID = f.IUAF_ID
	JOIN [pgl].[dbo].[IPL_UNIT_AREA_CLASS] c ON d.IUAFD_AREA_CLASS_ID = c.IUAC_ID
WHERE 
	f.IUAF_ID = 1
GROUP BY c.IUAC_CODE, c.IUAC_NAME
ORDER BY c.IUAC_CODE
GO 

-- ======= KWT_TARIF_IPL 
DELETE FROM KWT_TARIF_IPL 
WHERE KODE_TIPE IN ( 
	SELECT KODE_TIPE 
	FROM KWT_TIPE_IPL 
	WHERE STATUS_BLOK = 1 
) 
GO 

INSERT INTO KWT_TARIF_IPL 
( 
	KEY_IPL, 
	KODE_SK, 
	KODE_TIPE, 
	TIPE_TARIF_IPL, 
	TARIF_IPL, 
	NILAI_DEPOSIT, 
	KET 
) 
SELECT 
	(d.IUAFD_SK + '-' + REPLACE(c.IUAC_CODE, ' ', '-')) AS KEY_IPL, 
	d.IUAFD_SK AS KODE_SK, 
	REPLACE(c.IUAC_CODE, ' ', '-') AS KODE_TIPE, 
	1 AS TIPE_TARIF_IPL, 
	d.IUAFD_TOT_VALUE AS TARIF_IPL, 
	0 AS NILAI_DEPOSIT, 
	c.IUAC_NAME AS KET 
FROM 
	[pgl].[dbo].[IPL_UNIT_AREA_FEE_DETAIL] d 
	LEFT JOIN [pgl].[dbo].[IPL_UNIT_AREA_CLASS] c ON d.IUAFD_AREA_CLASS_ID = c.IUAC_ID 
WHERE 
	d.IUAFD_FEE_ID = 1
ORDER BY KEY_IPL ASC 
GO 

-- ====================== KWT_PEMBAYARAN_AI ====================== 
DELETE FROM KWT_PEMBAYARAN_AI WHERE TRX = 1 
GO 
INSERT INTO KWT_PEMBAYARAN_AI 
( 
	ID_PEMBAYARAN, 
	TRX, 
	NO_INVOICE, 
	TGL_JATUH_TEMPO, 
	
	PERIODE_TAG, 
	PERIODE_IPL_AWAL, 
	PERIODE_IPL_AKHIR, 
	JUMLAH_PERIODE_IPL, 
	
	NO_PELANGGAN, 
	
	KODE_SEKTOR, 
	KODE_CLUSTER, 
	KODE_BLOK, 
	STATUS_BLOK, 
	
	AKTIF_IPL, 

	LUAS_KAVLING, 
	TARIF_IPL, 
	
	NO_KWITANSI, 
	USER_BAYAR,
	TGL_BAYAR_BANK, 
	TGL_BAYAR_SYS, 
	KET_BAYAR, 
	
	JUMLAH_IPL, 
	ADM, 
	JUMLAH_BAYAR, 
	
	--DISKON_PERSEN_IPL, 
	DISKON_IPL, 
	TGL_DISKON_IPL, 
	USER_DISKON_IPL, 
	KET_DISKON_IPL,
	
	PERSEN_PPN, 
	NILAI_PPN, 
	
	NO_FP, 
	TGL_FP, 
	TGL_POST_FP, 
	STATUS_BAYAR, 
	
	KET_IVC, 
	
	USER_MODIFIED, 
	MODIFIED_DATE, 
	USER_CREATED, 
	CREATED_DATE, 
	
	ID_TEMP 
) 
SELECT 
	('1#' + CAST((i.IUI_YEAR*100 + i.IUI_MONTH) AS VARCHAR) + '#' + a.IUA_CODE) AS ID_PEMBAYARAN, 
	1 AS TRX, 
	i.IUI_NO AS NO_INVOICE, 
	i.IUI_DUE AS TGL_JATUH_TEMPO, 
	
	CAST((i.IUI_YEAR*100 + i.IUI_MONTH) AS VARCHAR) AS PERIODE_TAG, 
	
	CONVERT(VARCHAR(6),i.IUI_START_PERIOD,112) AS PERIODE_IPL_AWAL, 
	CONVERT(VARCHAR(6),i.IUI_END_PERIOD,112) AS PERIODE_IPL_AKHIR, 
	DATEDIFF(MONTH, i.IUI_START_PERIOD, i.IUI_END_PERIOD) + 1 AS JUMLAH_PERIODE_IPL, 
	
	a.IUA_CODE AS NO_PELANGGAN, 
	
	a.IUA_SECTOR_ID AS KODE_SEKTOR, 
	a.IUA_CLUSTER_ID AS KODE_CLUSTER, 
	a.IUA_CODE AS KODE_BLOK, 
	1 AS STATUS_BLOK, 
	
	1 AS AKTIF_IPL, 

	i.IUI_AREA_SQUARE AS LUAS_KAVLING, 
	i.IUI_UNIT_PRICE AS TARIF_IPL, 
	
	r.IUR_NO AS NO_KWITANSI, 
	UPPER(k.CUSR_NAME) AS USER_BAYAR, 
	r.IUR_PAYMENT_DATE AS TGL_BAYAR_BANK, 
	r.IUR_CREATED AS TGL_BAYAR_SYS, 
	r.IUR_DESC AS KET_BAYAR, 
	
	i.IUI_TOTAL_PRICE AS JUMLAH_IPL, 
	i.IUI_ADM AS ADM, 
	(CASE WHEN r.IUR_ID IS NULL THEN 0 ELSE i.IUI_TOTAL_PAYMENT END) AS JUMLAH_BAYAR, 
	
	i.IUI_DISC AS DISKON_IPL, 
	i.IUI_REVISED_DATE AS TGL_DISKON_IPL, 
	(CASE WHEN i.IUI_DISC > 0 THEN 'SYSTEM' END) AS USER_DISKON_IPL, 
	i.IUI_REVISED_DESC AS KET_DISKON_IPL, 
	
	(CASE WHEN i.IUI_PPN_PERSEN = 0 THEN 10 ELSE i.IUI_PPN_PERSEN END) AS PERSEN_PPN, 
	i.IUI_PPN AS NILAI_PPN, 
	
	i.SUI_TAX_NO AS NO_FP, 
	i.SUI_TAX_PROCEED_DATE AS TGL_FP, 
	i.SUI_TAX_PROCEED_DATE AS TGL_POST_FP, 
	(CASE WHEN r.IUR_ID IS NOT NULL THEN 1 ELSE 0 END) AS STATUS_BAYAR, 
	
	i.IUI_DESC AS KET_IVC, 
	
	m.CUSR_ID AS USER_MODIFIED, 
	i.IUI_LAST_MODIFIED AS MODIFIED_DATE, 
	c.CUSR_ID AS USER_CREATED, 
	i.IUI_CREATED AS CREATED_DATE, 
	
	a.IUA_ID AS ID_TEMP 
	
FROM 
	[pgl].[dbo].[IPL_UNIT_INVOICE] i 
	JOIN [pgl].[dbo].[IPL_UNIT_AREA_OCCUPIED] o ON i.IUI_OCCUPIED_ID = o.IUAO_ID 
	JOIN [pgl].[dbo].[IPL_UNIT_AREA] a ON o.IUAO_AREA_ID = a.IUA_ID 
	LEFT JOIN [pgl].[dbo].[IPL_UNIT_RECEIPT] r ON i.IUI_ID = r.IUR_INVOICE_ID 
	
	LEFT JOIN [pgl].[dbo].[CLASP_USER] k ON r.IUR_CASHIER_ID = k.CUSR_ID 
	LEFT JOIN [pgl].[dbo].[CLASP_USER] m ON i.IUI_OP_MODIFIED = m.CUSR_ID 
	LEFT JOIN [pgl].[dbo].[CLASP_USER] c ON i.IUI_OP_CREATED = c.CUSR_ID 
WHERE 
	i.IUI_INVOICETYPE_ID = 1 AND 
	(
		(
			i.IUI_YEAR = 2014 AND 
			1 = ( 
				CASE WHEN r.IUR_IS_CANCELED = 'Y' THEN 0 ELSE 1 END 
			) 
		)
		OR
		(
			i.IUI_YEAR != 2014 AND 
			r.IUR_INVOICE_ID IS NULL
		)
	) 

	--/*
	AND IUI_ID != 126286 --PR/PB7A-09-10 01-2012 DIBATALKAN
	AND IUI_ID != 126283 --PR/PB7A-09-10 01-2012 DIBATALKAN
	AND IUI_ID != 141155 --B3/CK-01 04-2014 DENGAN ID 143371
	AND IUI_ID != 143375 --B3/CK-10 04-2014 DENGAN ID 134250
	AND IUI_ID != 144116 --MP/B7-08 04-2014 DENGAN ID 146460 
	--*/

ORDER BY i.IUI_MONTH ASC 
GO 


