-- KWT_PELANGGAN ALL
TRUNCATE TABLE KWT_PELANGGAN
GO
INSERT INTO KWT_PELANGGAN
(
	NO_PELANGGAN, INFO_TAGIHAN, NAMA_PELANGGAN, NPWP, NO_TELEPON, NO_HP, DEBET_BANK, 
	KODE_BANK, NO_REKENING, KODE_ZONA, TGL_PEMUTUSAN, KETERANGAN, KEY_AIR, CREATED_DATE,
	
	KODE_SEKTOR, 
	KODE_CLUSTER, 
	KODE_BLOK,
	LUAS_KAVLING, 
	LUAS_BANGUNAN, 
	STATUS_BLOK,
	
	KEY_IPL,
	TIPE_AIR, 
	TIPE_IPL, 
	NO_KTP,
	ALAMAT,
	
	TGL_PPJB,
	PERIODE_PUTUS,
	PETUGAS,
	
	AKTIF_AIR,
	AKTIF_IPL,
	
	PAKAI_SM,
	SM_NAMA_PELANGGAN,
	SM_ALAMAT,
	SM_NO_TELEPON,
	SM_NO_HP
)
SELECT 
	NO_PELANGGAN, INFO_TAGIHAN, NAMA_PELANGGAN, NPWP, NO_TELEPON, NO_HP, DEBET_BANK, 
	KODE_BANK, NO_REKENING, KODE_ZONA, TGL_PEMUTUSAN, KETERANGAN, KEY_AIR, CREATED_DATE,
	
	KODE_SEKTOR, 
	KODE_CLUSTER, 
	KODE_BLOK,
	ISNULL(LUAS_KAVLING, 0) AS LUAS_KAVLING, 
	ISNULL(LUAS_BANGUNAN, 0) AS LUAS_BANGUNAN, 
	'4' AS STATUS_BLOK,
	
	KEY_KEB AS KEY_IPL,
	SUBSTRING(KEY_AIR,CHARINDEX('-',KEY_AIR)+1,10) AS TIPE_AIR,
	SUBSTRING(TIPE_KEB,CHARINDEX('-',TIPE_KEB)+1,10) AS TIPE_IPL, 
	NO_PELANGGAN AS NO_KTP, 
	ALAMAT_1 + ' ' + ALAMAT_2 AS ALAMAT, 
	
	TGL_SERAHTERIMA AS TGL_PPJB,
	(RIGHT(PERIODE_PUTUS,4) + LEFT(PERIODE_PUTUS,2)) AS PERIODE_PUTUS,
	PETUGAS,
	
	'1' AS AKTIF_AIR,
	'1' AS AKTIF_IPL,
	
	NULL AS PAKAI_SM ,
	NAMA_PELANGGAN AS SM_NAMA_PELANGGAN ,
	ALAMAT_1 + ' ' + ALAMAT_2 AS SM_ALAMAT ,
	NO_TELEPON AS SM_NO_TELEPON ,
	NO_HP AS SM_NO_HP
	
FROM KWT_PELANGGAN_BACKUP
GO

-- KWT_PEMBAYARAN_AI ALL
TRUNCATE TABLE KWT_PEMBAYARAN_AI
GO
INSERT INTO KWT_PEMBAYARAN_AI
(
	NO_PELANGGAN, KEY_AIR, KODE_SEKTOR, KODE_CLUSTER, KODE_BLOK, KODE_ZONA, NO_FAKTUR_PAJAK, 
	TGL_FAKTUR_PAJAK, STATUS_BAYAR, NO_KWITANSI, 
	BAYAR_MELALUI, JENIS_BAYAR, TGL_BAYAR, TGL_TERIMA_BANK, KASIR, 
	STATUS_EDIT, TGL_EDIT, USER_EDIT, STATUS_BATAL, TGL_BATAL, USER_BATAL, 
	
	TRX,
	ID_PEMBAYARAN,
	PERIODE,
	PERIODE_AWAL,
	PERIODE_AKHIR,
	JUMLAH_PERIODE,
	
	STAND_LALU, 
	STAND_ANGKAT, 
	STAND_AKHIR, 
	BLOK1, 
	BLOK2, 
	BLOK3, 
	BLOK4, 
	STAND_MIN_PAKAI, 
	JUMLAH_AIR, 
	ABONEMEN, 
	DENDA, 
	ADMINISTRASI, 
	JUMLAH_BAYAR, 
	NILAI_PPN, 
	
	STATUS_POST_PB,
	TGL_POST_FP,
	
	STATUS_CETAK_KWT,
	KETERANGAN_BAYAR,
	
	PERSEN_PPN,
	
	DISKON_PERSEN_AIR, 
	DISKON_RUPIAH_AIR, 
	TGL_DISKON_AIR, 
	USER_DISKON_AIR,
	
	DISKON_PERSEN_IPL, 
	DISKON_RUPIAH_IPL, 
	TGL_DISKON_IPL, 
	USER_DISKON_IPL, 
	
	KETERANGAN_DISKON, 
	
	TARIF1, 
	TARIF2, 
	TARIF3, 
	TARIF4, 
	JUMLAH_IPL,
	TARIF_MIN_PAKAI,
	KEY_IPL,
	STATUS_BLOK,
	
	LUAS_KAVLING,
	TARIF_IPL,
	
	AKTIF_AIR,
	AKTIF_IPL
) 
SELECT 
	b.NO_PELANGGAN, b.KEY_AIR, b.KODE_SEKTOR, b.KODE_CLUSTER, b.KODE_BLOK, b.KODE_ZONA, b.NO_FAKTUR_PAJAK,
	b.TGL_FAKTUR_PAJAK, b.STATUS_BAYAR, b.NO_KWITANSI,
	b.BAYAR_MELALUI, b.JENIS_BAYAR, b.TGL_BAYAR, b.TGL_TERIMA_BANK, b.KASIR,
	b.STATUS_EDIT, b.TGL_EDIT, b.USER_EDIT, b.STATUS_BATAL, b.TGL_BATAL, b.USER_BATAL,
	
	'4' AS TRX,
	'4#' + RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) + '#' + b.NO_PELANGGAN AS ID_PEMBAYARAN,
	RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) AS PERIODE,
	RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) AS PERIODE_AWAL,
	RIGHT(b.PERIODE,4) + LEFT(b.PERIODE,2) AS PERIODE_AKHIR,
	1 AS JUMLAH_PERIODE,
	
	ISNULL(b.STAND_LALU, 0) AS STAND_LALU, 
	ISNULL(b.STAND_ANGKAT, 0) AS STAND_ANGKAT, 
	ISNULL(b.STAND_AKHIR, 0) AS STAND_AKHIR,
	ISNULL(b.BLOK1, 0) AS BLOK1, 
	ISNULL(b.BLOK2, 0) AS BLOK2, 
	ISNULL(b.BLOK3, 0) AS BLOK3, 
	ISNULL(b.BLOK4, 0) AS BLOK4, 
	ISNULL(b.STAND_MIN_PAKAI, 0) AS STAND_MIN_PAKAI,
	ISNULL(b.JUMLAH_AIR, 0) AS JUMLAH_AIR, 
	ISNULL(b.ABONEMEN, 0) AS ABONEMEN, 
	ISNULL(b.DENDA, 0) AS DENDA, 
	ISNULL(b.ADMINISTRASI, 0) AS ADMINISTRASI, 
	ISNULL(b.JUMLAH_BAYAR, 0) AS JUMLAH_BAYAR, 
	ISNULL(b.NILAI_PPN, 0) AS NILAI_PPN, 	
	
	b.STATUS_POS AS STATUS_POST_PB,
	b.TGL_POSTING_FAKTUR_PAJAK AS TGL_POST_FP,
	
	b.JUMLAH_CETAK AS STATUS_CETAK_KWT,
	b.KETERANGAN AS KETERANGAN_BAYAR,
	
	ISNULL(b.PROSEN_PPN, 0) AS PERSEN_PPN,
	
	ISNULL(b.DISC_PERSEN, 0) AS DISKON_PERSEN_AIR, 
	ISNULL(b.DISC_RUPIAH, 0) AS DISKON_RUPIAH_AIR, 
	b.TGL_DISC AS TGL_DISKON_AIR, 
	b.USER_DISC AS USER_DISKON_AIR,
	
	ISNULL(b.DISC_PERSEN_IPL, 0) AS DISKON_PERSEN_IPL, 
	ISNULL(b.DISC_RUPIAH_IPL, 0) AS DISKON_RUPIAH_IPL, 
	b.TGL_DISC_IPL AS TGL_DISKON_IPL, 
	b.USER_DISC_IPL AS USER_DISKON_IPL, 
	
	b.KET_DISCOUNT AS KETERANGAN_DISKON, 
	
	ISNULL(b.TARIP1, 0) AS TARIF1, 
	ISNULL(b.TARIP2, 0) AS TARIF2, 
	ISNULL(b.TARIP3, 0) AS TARIF3, 
	ISNULL(b.TARIP4, 0) AS TARIF4, 
	ISNULL(b.NILAI_SAMPAH, 0) AS JUMLAH_IPL,
	ISNULL(b.TARIP_MIN_PAKAI, 0) AS TARIF_MIN_PAKAI, 
	b.KEY_KEB AS KEY_IPL,
	'4' AS STATUS_BLOK,
	
	ISNULL(p.LUAS_KAVLING, 0) AS LUAS_KAVLING,
	ISNULL(i.TARIF_IPL, 0) AS TARIF_IPL,
	
	'1' AS AKTIF_AIR,
	'1' AS AKTIF_IPL
	
FROM 
	KWT_PEMBAYARAN_BACKUP b
	LEFT JOIN KWT_PELANGGAN p ON b.NO_PELANGGAN = p.NO_PELANGGAN
	LEFT JOIN KWT_TARIF_IPL i ON b.KEY_KEB = i.KEY_IPL
	LEFT JOIN KWT_TIPE_IPL t ON i.KODE_TIPE = t.KODE_TIPE
WHERE
	PERIODE IN ('082013','092013','102013','112013','122013')
	--PERIODE IN ('082013','092013','102013')
GO

-- CLEAN DATA
--=========================
DELETE FROM KWT_PELANGGAN WHERE NO_PELANGGAN = '071200016130'
DELETE FROM KWT_PEMBAYARAN_AI WHERE NO_PELANGGAN = '071200016130'
INSERT INTO KWT_PELANGGAN_IMP (NO_PELANGGAN, KODE_BLOK, STATUS_BLOK, CREATED_DATE) VALUES 
('AA/BB-CC', 'AA/BB-CC', '1', GETDATE()), 
('DD/EE-FF', 'DD/EE-FF', '1', GETDATE()), 
('GG/HH-II', 'GG/HH-II', '1', GETDATE())
GO

-- UPDATE PERIODE
--=========================
UPDATE KWT_DISKON_KHUSUS 
	SET
		PERIODE_AWAL = RIGHT(PERIODE_AWAL,4) + LEFT(PERIODE_AWAL,2),
		PERIODE_AKHIR = RIGHT(PERIODE_AKHIR,4) + LEFT(PERIODE_AKHIR,2)
GO

-- INSERT & UPDATE
--=========================
-- KWT_BLOK ALL
TRUNCATE TABLE KWT_BLOK
GO
INSERT INTO KWT_BLOK 
(
	KODE_BLOK, KODE_SEKTOR, KODE_CLUSTER, LUAS_KAVLING, LUAS_BANGUNAN, 
	STATUS_BLOK
)
SELECT 
	KODE_BLOK, KODE_SEKTOR, KODE_CLUSTER, LUAS_KAVLING, LUAS_BANGUNAN,
	'4' AS STATUS_BLOK
FROM KWT_PELANGGAN_BACKUP a
WHERE
	(SELECT COUNT(KODE_BLOK) FROM KWT_PELANGGAN_BACKUP WHERE KODE_BLOK = a.KODE_BLOK) = 1
ORDER BY CREATED_DATE DESC
GO

-- PELANGGAN_LOOKUP
TRUNCATE TABLE KWT_PELANGGAN_LOOKUP
GO
INSERT INTO KWT_PELANGGAN_LOOKUP 
(
	NO_KTP, NAMA_PELANGGAN, NPWP, ALAMAT, NO_TELEPON, NO_HP, KODE_BANK, NO_REKENING
)
SELECT 
	NO_KTP, NAMA_PELANGGAN, NPWP, ALAMAT, NO_TELEPON, NO_HP, KODE_BANK, NO_REKENING 
FROM KWT_PELANGGAN
GO

-- KWT_PELANGGAN
UPDATE KWT_PELANGGAN  
SET AKTIF_AIR = NULL
WHERE KEY_AIR LIKE '%X0%'
GO
UPDATE KWT_PELANGGAN  
SET AKTIF_IPL = NULL
WHERE KEY_IPL LIKE '%X0%'
GO

-- KWT_PEMBAYARAN_AI
UPDATE KWT_PEMBAYARAN_AI  
SET AKTIF_AIR = NULL
WHERE ABONEMEN < 1
GO
UPDATE KWT_PEMBAYARAN_AI  
SET AKTIF_IPL = NULL
WHERE JUMLAH_IPL < 1
GO

-- IPL
UPDATE KWT_TARIF_IPL SET TIPE_TARIF_IPL = '1' WHERE KODE_TIPE LIKE '%BB%' OR KODE_TIPE LIKE '%BS%'
UPDATE KWT_TIPE_IPL
SET GOLONGAN = '1'
WHERE 
	KODE_TIPE LIKE '%KB%' OR 
	KODE_TIPE LIKE '%KS%' OR
	KODE_TIPE LIKE '%MB%' OR 
	KODE_TIPE LIKE '%MS%' OR
	KODE_TIPE LIKE '%BB%' OR 
	KODE_TIPE LIKE '%BS%'

-- AIR
UPDATE KWT_TIPE_AIR SET GOLONGAN = '1' WHERE KODE_TIPE LIKE '%B%' OR KODE_TIPE LIKE '%BB%'
UPDATE KWT_TARIF_AIR
SET
	ABONEMEN = 0,
	BLOK1 = 0,
	BLOK2 = 0,
	BLOK3 = 0,
	BLOK4 = 0,
	STAND_MIN_PAKAI = 0,
	TARIF1 = 0,
	TARIF2 = 0,
	TARIF3 = 0,
	TARIF4 = 0
WHERE KODE_TIPE = 'X0'

UPDATE KWT_TARIF_AIR SET DENDA_STANDAR_AIR = 1, DENDA_BISNIS_AIR = 3
GO
UPDATE KWT_TARIF_IPL SET DENDA_STANDAR_IPL = 1, DENDA_BISNIS_IPL = 3
GO

UPDATE KWT_PEMBAYARAN_AI 
SET JUMLAH_AIR = ((BLOK1 * TARIF1) + (BLOK2 * TARIF2) + (BLOK3 * TARIF3) + (BLOK4 * TARIF4) + (STAND_MIN_PAKAI * TARIF_MIN_PAKAI))
WHERE STATUS_BAYAR IS NULL
GO

UPDATE KWT_PEMBAYARAN_AI 
SET JUMLAH_BAYAR = ( (JUMLAH_AIR + ABONEMEN + JUMLAH_IPL + ADMINISTRASI + DENDA) - (DISKON_RUPIAH_AIR + DISKON_RUPIAH_IPL) )
WHERE STATUS_BAYAR = '2'
GO

UPDATE KWT_PEMBAYARAN_AI 
SET JENIS_BAYAR = '4'
WHERE
	STATUS_BAYAR = '2' AND 
	JENIS_BAYAR IS NULL
GO



