-- ====================== KWT_PEMBAYARAN_AI ====================== 
DELETE FROM KWT_PEMBAYARAN_AI WHERE TRX = 5 
GO 
INSERT INTO KWT_PEMBAYARAN_AI 
( 
	ID_PEMBAYARAN, 
	TRX, 
	NO_INVOICE, 
	TGL_JATUH_TEMPO, 
	
	PERIODE_TAG, 
	PERIODE_IPL_AWAL, 
	PERIODE_IPL_AKHIR, 
	JUMLAH_PERIODE_IPL, 
	
	NO_PELANGGAN, 
	
	KODE_SEKTOR, 
	KODE_CLUSTER, 
	KODE_BLOK, 
	STATUS_BLOK, 
	
	AKTIF_IPL, 
	
	LUAS_KAVLING, 
	
	NO_KWITANSI, 
	USER_BAYAR,
	TGL_BAYAR_BANK, 
	TGL_BAYAR_SYS, 
	KET_BAYAR, 
	
	JUMLAH_IPL, 
	ADM, 
	JUMLAH_BAYAR, 
	
	--DISKON_PERSEN_IPL, 
	DISKON_IPL, 
	TGL_DISKON_IPL, 
	USER_DISKON_IPL, 
	KET_DISKON_IPL, 
	
	PERSEN_PPN, 
	NILAI_PPN, 
	
	NO_FP, 
	TGL_FP, 
	TGL_POST_FP, 
	STATUS_BAYAR, 
	
	KET_IVC, 
	
	USER_MODIFIED, 
	MODIFIED_DATE, 
	USER_CREATED, 
	CREATED_DATE, 
	
	ID_TEMP 
) 
SELECT 
	('5#' + CAST((i.IUI_YEAR*100 + i.IUI_MONTH) AS VARCHAR) + '#' + a.IUA_CODE) AS ID_PEMBAYARAN, 
	5 AS TRX, 
	i.IUI_NO AS NO_INVOICE, 
	i.IUI_DUE AS TGL_JATUH_TEMPO, 
	
	CAST((i.IUI_YEAR*100 + i.IUI_MONTH) AS VARCHAR) AS PERIODE_TAG, 
	
	CONVERT(VARCHAR(6),i.IUI_START_PERIOD,112) AS PERIODE_IPL_AWAL, 
	CONVERT(VARCHAR(6),i.IUI_END_PERIOD,112) AS PERIODE_IPL_AKHIR, 
	DATEDIFF(MONTH, i.IUI_START_PERIOD, i.IUI_END_PERIOD) + 1 AS JUMLAH_PERIODE_IPL, 
	
	a.IUA_CODE AS NO_PELANGGAN, 
	
	a.IUA_SECTOR_ID AS KODE_SEKTOR, 
	a.IUA_CLUSTER_ID AS KODE_CLUSTER, 
	a.IUA_CODE AS KODE_BLOK, 
	2 AS STATUS_BLOK, 
	
	1 AS AKTIF_IPL, 
	
	i.IUI_AREA_SQUARE AS LUAS_KAVLING, 
	
	r.IUR_NO AS NO_KWITANSI, 
	UPPER(k.CUSR_NAME) AS USER_BAYAR, 
	r.IUR_PAYMENT_DATE AS TGL_BAYAR_BANK, 
	r.IUR_CREATED AS TGL_BAYAR_SYS, 
	r.IUR_DESC AS KET_BAYAR, 
	
	i.IUI_TOTAL_PRICE AS JUMLAH_IPL, 
	i.IUI_ADM AS ADM, 
	(CASE WHEN r.IUR_ID IS NULL THEN 0 ELSE i.IUI_TOTAL_PAYMENT END) AS JUMLAH_BAYAR, 
	
	i.IUI_DISC AS DISKON_IPL, 
	i.IUI_REVISED_DATE AS TGL_DISKON_IPL, 
	(CASE WHEN i.IUI_DISC > 0 THEN 'SYSTEM' END) AS USER_DISKON_IPL, 
	i.IUI_REVISED_DESC AS KET_DISKON_IPL, 
	
	i.IUI_PPN_PERSEN AS PERSEN_PPN, 
	i.IUI_PPN AS NILAI_PPN, 
	
	i.SUI_TAX_NO AS NO_FP, 
	i.SUI_TAX_PROCEED_DATE AS TGL_FP, 
	i.SUI_TAX_PROCEED_DATE AS TGL_POST_FP, 
	(CASE WHEN r.IUR_ID IS NOT NULL THEN 1 ELSE 0 END) AS STATUS_BAYAR, 
	
	i.IUI_DESC AS KET_IVC, 
	
	m.CUSR_ID AS USER_MODIFIED, 
	i.IUI_LAST_MODIFIED AS MODIFIED_DATE, 
	c.CUSR_ID AS USER_CREATED, 
	i.IUI_CREATED AS CREATED_DATE, 
	
	a.IUA_ID AS ID_TEMP 
	
FROM 
	[pgl].[dbo].[IPL_UNIT_INVOICE] i 
	JOIN [pgl].[dbo].[IPL_UNIT_AREA_OCCUPIED] o ON i.IUI_OCCUPIED_ID = o.IUAO_ID 
	JOIN [pgl].[dbo].[IPL_UNIT_AREA] a ON o.IUAO_AREA_ID = a.IUA_ID 
	LEFT JOIN [pgl].[dbo].[IPL_UNIT_RECEIPT] r ON i.IUI_ID = r.IUR_INVOICE_ID 
	
	LEFT JOIN [pgl].[dbo].[CLASP_USER] k ON r.IUR_CASHIER_ID = k.CUSR_ID 
	LEFT JOIN [pgl].[dbo].[CLASP_USER] m ON i.IUI_OP_MODIFIED = m.CUSR_ID 
	LEFT JOIN [pgl].[dbo].[CLASP_USER] c ON i.IUI_OP_CREATED = c.CUSR_ID 
WHERE 
i.IUI_INVOICETYPE_ID = 5 AND -- Change to 5
(
		(
			i.IUI_YEAR = 2014 AND 
			1 = ( 
				CASE WHEN r.IUR_IS_CANCELED = 'Y' THEN 0 ELSE 1 END 
			) 
		)
		OR
		(
			i.IUI_YEAR != 2014 AND 
			r.IUR_INVOICE_ID IS NULL
		)
	)
	
	--/*
	AND i.IUI_ID != 138808 -- <= 138806 B7/A1-12 DOUBLE PERIODE 
	--*/
	
ORDER BY i.IUI_MONTH ASC 
GO 


