-- ====================== KWT_PERIODE_DEPOSIT ====================== 
DELETE FROM KWT_PERIODE_DEPOSIT 
GO 
INSERT INTO KWT_PERIODE_DEPOSIT 
( 
	ID_DEPOSIT, 
	TRX, 
	KODE_BLOK, 
	PERIODE_IPL_AWAL, 
	PERIODE_IPL_AKHIR, 
	JUMLAH_PERIODE_IPL, 
	KET_DEPOSIT, 
	STATUS_PROSES, 
	CREATED_DATE, 
	ID_TEMP 
) 
SELECT 
	('7#' + CONVERT(VARCHAR(6),b.IUBP_START_PERIOD,112) + '#' + a.IUA_CODE) AS ID_DEPOSIT, 
	7 AS TRX, 
	
	a.IUA_CODE AS KODE_BLOK, 
	CONVERT(VARCHAR(6),b.IUBP_START_PERIOD,112) AS PERIODE_IPL_AWAL, 
	CONVERT(VARCHAR(6),b.IUBP_END_PERIOD,112) AS PERIODE_IPL_AKHIR, 
	b.IUBP_PERIOD AS JUMLAH_PERIODE_IPL, 
	b.IUBP_DESC AS KET_DEPOSIT, 
	
	(CASE WHEN b.IUBP_IS_PROCEED = 'Y' THEN 1 ELSE 0 END) AS STATUS_PROSES, 
	b.IUBP_CREATED AS CREATED_DATE, 
	b.IUBP_AREA_OCCUPIED_ID AS ID_TEMP 
FROM 
	[pgl].[dbo].[IPL_UNIT_BUILD_PERIOD] b 
	JOIN [pgl].[dbo].[IPL_UNIT_AREA_OCCUPIED] o ON b.IUBP_AREA_OCCUPIED_ID = o.IUAO_ID 
	JOIN [pgl].[dbo].[IPL_UNIT_AREA] a ON o.IUAO_AREA_ID = a.IUA_ID 
WHERE 
	a.IUA_CODE IN ( 
		SELECT DISTINCT(KODE_BLOK) 
		FROM KWT_PEMBAYARAN_AI WHERE TRX IN (5,7) 
	) 
ORDER BY a.IUA_CODE, b.IUBP_END_PERIOD 
GO 

-- ====================== UPDATE NILAI_DEPOSIT ====================== 
UPDATE p 
	SET 
		p.NILAI_DEPOSIT = i.IUI_TOTAL_PAYMENT, 
		p.TIPE_DEPOSIT = (CASE WHEN i.IUI_TOTAL_PAYMENT > 0 THEN '1' ELSE '0' END) 
FROM 
	KWT_PERIODE_DEPOSIT p 
	JOIN [pgl].[dbo].[IPL_UNIT_INVOICE] i ON p.ID_TEMP = i.IUI_OCCUPIED_ID 
WHERE 
	p.TRX = 7 
	AND i.IUI_INVOICETYPE_ID = 3 
GO 

-- ====================== UPDATE NILAI_LAIN-LAIN ====================== 
UPDATE p 
	SET 
		p.NILAI_LAIN_LAIN = i.IUI_TOTAL_PAYMENT, 
		p.KET_LAIN_LAIN = i.IUI_DESC 
FROM 
	KWT_PERIODE_DEPOSIT p 
	JOIN [pgl].[dbo].[IPL_UNIT_INVOICE] i ON p.ID_TEMP = i.IUI_OCCUPIED_ID 
WHERE 
	p.TRX = 5 
	AND i.IUI_INVOICETYPE_ID = 5 
GO 
	
	
	
	