UPDATE 
	KWT_PEMBAYARAN_AI
SET 
	STATUS_BAYAR = NULL
WHERE 
	(
		RIGHT(CONVERT(VARCHAR(10), TGL_TERIMA_BANK, 105), 7) = '11-2013' OR 
		RIGHT(CONVERT(VARCHAR(10), TGL_TERIMA_BANK, 105), 7) = '04-2014'
	) AND
	STATUS_BAYAR IS NOT NULL AND 
	BAYAR_MELALUI IS NOT NULL
GO

--
UPDATE 
	KWT_PEMBAYARAN_AI
SET 
	STATUS_BAYAR = NULL
WHERE 
	(
		RIGHT(CONVERT(VARCHAR(10), TGL_TERIMA_BANK, 105), 7) = '04-2013'
	) AND
	STATUS_BAYAR IS NOT NULL AND 
	BAYAR_MELALUI IS NOT NULL
GO